#pragma kernel CSMain

float2 Resolution;
StructuredBuffer<float3> Buff;
RWTexture2D<float4> Result;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    Result.GetDimensions(w, h);
    Resolution = float2(w, h);
    
    Result[id.xy] = float4(id.xy, 0, 1);
    Result[id.xy] = float4(Buff[id.x + id.y * 2], 1);
    /*
    Result[id.xy] = float4(
        id.z == 0 ? 1 : 0,
        id.z == 1 ? 1 : 0,
        id.z == 2 ? 1 : 0,
        1);
    */
}
