#define NCLIP 1
#define FCLIP 30

Texture2D<float4> Input;
RWTexture2D<float> Depth;
RWTexture2D<float2> TLookup, Transformed;
RWTexture2D<float4> Result;

bool DEBUG;
float2 RESOLUTION, LINE_CLIP;
float3 OFFSET;
float PI, PI2, SEARCH_ITERATIONS;




#pragma kernel Project

int2 project(int2 tc, out float d)
{
    float2 uv = tc / RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = Input[tc].a * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));

    P -= OFFSET;
    // P = mul(TR, P);
    d = length(P);

    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z));

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI);
    a.x += 0.5;

    return (int2)round(a * RESOLUTION);
}

void DrawLine(int2 p0, int2 p1, float2 id)
{
    // clip the line by length
    if (distance(p0, p1) < LINE_CLIP.x || distance(p0, p1) > LINE_CLIP.y)
        return;

    // Iterators, counters required by algorithm
    int x, y, dx, dy, dx1, dy1, px, py, xe, ye, i;

    // Calculate line deltas
    dx = p1.x - p0.x;
    dy = p1.y - p0.y;

    // Create a positive copy of deltas (makes iterating easier)
    dx1 = abs(dx);
    dy1 = abs(dy);

    // Calculate error intervals for both axis
    px = 2 * dy1 - dx1;
    py = 2 * dx1 - dy1;

    // The line is X-axis dominant
    if (dy1 <= dx1)
    {
        // Line is rdawn left to right
        if (dx >= 0)
        {
            x = p0.x; y = p0.y; xe = p1.x;
        }
        else
        {
            // Line is rdawn right to left (swap ends)
            x = p1.x; y = p1.y; xe = p0.x;
        }

        // Result[uint2(x, y)] = float4(1, 1, 0, 0); // Draw first pixel

        // Rasterize the line
        for (int i = 0; x < xe; i++) {
            x = x + 1;

            // Deal with octants...
            if (px < 0)
            {
                px = px + 2 * dy1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    y = y + 1;
                }
                else
                {
                    y = y - 1;
                }

                px = px + 2 * (dy1 - dx1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            TLookup[int2(x, y)] = id;
        }
    }
    else
    {
        // The line is Y-axis dominant
        // Line is rdawn bottom to top
        if (dy >= 0)
        {
            x = p0.x; y = p0.y; ye = p1.y;
        }
        else
        {
            // Line is rdawn top to bottom
            x = p1.x; y = p1.y; ye = p0.y;
        }

        // Result[uint2(x, y)] = float4(1, 1, 0, 0); // Draw first pixel

        // Prevent unrolling of loop
        if (y == ye)
            return;

        // Rasterize the line
        for (int i = 0; y < ye; i++)
        {
            y = y + 1;

            // Deal with octants...
            if (py <= 0)
            {
                py = py + 2 * dx1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    x = x + 1;
                }
                else
                {
                    x = x - 1;
                }

                py = py + 2 * (dx1 - dy1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            TLookup[int2(x, y)] = id;
        }
    }
}

[numthreads(8, 8, 1)]
void Project(uint3 id : SV_DispatchThreadID)
{
    // project triangle
    float d0, d1, d2;
    int2 off = int2(1, 0);
    int2 v0 = project(id.xy, d0);
    int2 v1 = project(id.xy + off, d1);
    int2 v2 = project(id.xy + off.yx, d2);

    // store the transformed lookup
    Transformed[id.xy] = v0;

    // render the point to the ouput texture (maybe not neccessary)
    float d = Depth[v0];
    if (d == 0 || d0 < d)
    {
        Result[v0] = Input[id.xy];
        Depth[v0] = d0;
    }

    // skip triangulation if verticies intersect
    if ((v0.x == v1.x && v0.y == v1.y) ||
        (v1.x == v2.x && v1.y == v2.y) ||
        (v2.x == v0.x && v2.y == v0.y))
        return;

    // store depth values
    Depth[v0] = d0;
    Depth[v1] = d1;
    Depth[v2] = d2;

    // draw triangle outline
    DrawLine(v0, v1, id.xy);
    DrawLine(v1, v2, id.xy);
    DrawLine(v2, v0, id.xy);
}




#pragma kernel Interpolate

// thanks to MBo for the idea: https://stackoverflow.com/a/61096648/13215204
float3 GetBarycentricCoordinates(int2 p, int2 v0, int2 v1, int2 v2)
{
    // calculate determinant
    float det = (v1.y - v2.y) * (v0.x - v2.x) + (v2.x - v1.x) * (v0.y - v2.y);

    // get barycentric coordinates (3rd one is implied)
    float lambda0 = ((v1.y - v2.y) * (p.x - v2.x) + (v2.x - v1.x) * (p.y - v2.y)) / det;
    float lambda1 = ((v2.y - v0.y) * (p.x - v2.x) + (v0.x - v2.x) * (p.y - v2.y)) / det;

    return float3(lambda0, lambda1, 1 - lambda0 - lambda1);
}

bool PointInTriangle(int2 p, int2 v0, int2 v1, int2 v2)
{
    float s = (v0.x - v2.x) * (p.y - v2.y) - (v0.y - v2.y) * (p.x - v2.x);
    float t = (v1.x - v0.x) * (p.y - v0.y) - (v1.y - v0.y) * (p.x - v0.x);

    if ((s < 0) != (t < 0) && s != 0 && t != 0)
        return false;

    float d = (v2.x - v1.x) * (p.y - v1.y) - (v2.y - v1.y) * (p.x - v1.x);
    return d == 0 || (d < 0) == (s + t <= 0);
}

bool OverlayPoint(int2 p, int2 p0)
{
    // check there's a transform at p
    int2 i0 = TLookup[p];
    if (!any(i0))
        return false;

    // set missing ids
    int2 i1 = i0 + int2(1, 0);
    int2 i2 = i0 + int2(0, 1);

    // get vertex coordinates
    int2 v0 = Transformed[i0];
    int2 v1 = Transformed[i1];
    int2 v2 = Transformed[i2];

    // get color and depth data
    float4 c0 = float4(Input[i0].rgb, Depth[i0]);
    float4 c1 = float4(Input[i1].rgb, Depth[i1]);
    float4 c2 = float4(Input[i2].rgb, Depth[i2]);

    float3 bc = GetBarycentricCoordinates(p0, v0, v1, v2);
    float4 c;

    // barycentric not inside first triangle
    if (bc.x < 0 || bc.y < 0 || bc.z < 0 || bc.x > 1 || bc.y > 1 || bc.z > 1)
    {
        // retrieve 4th quad vertex
        int2 i3 = i0 + int2(1, 1);
        int2 v3 = Transformed[i3];
        float4 c3 = float4(Input[i3].rgb, Depth[i3]);

        // apply weighting / interpolation
        bc = GetBarycentricCoordinates(p0, v1, v2, v3);
        c = c1 * bc.x + c2 * bc.y + c3 * bc.z;

        if (DEBUG)
            c = float4(0.5, 0.25, 0, 1000);
    }
    else
    {
        // apply weighting / interpolation
        c = c0 * bc.x + c1 * bc.y + c2 * bc.z;

        if (DEBUG)
            c = float4(0, 0.25, 0.5, 1000);
    }

    // fetch depth to be overwritten
    float od = Depth[p0];

    // already a closer point rasterized
    if (od != 0 && c.z > od)
        return false;

    // no color info: NOT TESTED
    if (!any(c.rgb))
        return true;

    // write to output
    Result[p0] = float4(c.rgb, 1);
    Depth[p0] = c.w;
    return true;
}

[numthreads(8, 8, 1)]
void Interpolate(uint3 id : SV_DispatchThreadID)
{
    // check current point
    if (OverlayPoint(id.xy, id.xy))
        return;

    // propagate upwards until intersection with triangle boundary
    for (int i = 0; i < SEARCH_ITERATIONS; i++)
    {
        if (OverlayPoint(int2(id.x, id.y + i), id.xy))
            break;
    }
}
