float PI, PI2, FOV, FCLIP;
float2 Rotation;
float3 Position;
float Off;
bool Fill;
bool Debug;

#pragma kernel Gnomonic;
#pragma kernel Projection

StructuredBuffer<float3> OffsetBuffer;
StructuredBuffer<float3> DebugOffsetBuffer;
Texture2DArray<float4> InputArray;
RWTexture2D<float4> Projected;
RWTexture2D<float4> Result;

[numthreads(8, 8, 1)]
void Projection(uint3 id : SV_DispatchThreadID)
{
    PI2 = PI * 2;
    uint InputWidth, InputHeight, TransWidth, TransHeight, _;
    InputArray.GetDimensions(InputWidth, InputHeight, _);
    Projected.GetDimensions(TransWidth, TransHeight);
    float2 InputRes = float2(InputWidth, InputHeight);
    float2 TransRes = float2(TransWidth, TransHeight);
    
    float3 inpIdx = float3(id.xy / TransRes * InputRes, id.z);
    
    float2 ll1 = id.yx / TransRes.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;
    
    float CP = InputArray[inpIdx].a * FCLIP;
    
    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P -= Position;
    P += OffsetBuffer[id.z];
    P += DebugOffsetBuffer[id.z];
    
    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float2 idx = round(a * TransRes);
    
    if (all(Projected[idx] == 0) || InputArray[inpIdx].a < Projected[idx].a)
    {
        if (Debug)
        {
            Projected[idx] = float4(
                sin(id.z),
                cos(id.z),
                tan(id.z),
                1);
        }
        else if (any(InputArray[inpIdx].xyz))
        {
            if (Fill)
            {
                float2 idxXP = float2(idx.x + Off, idx.y);
                float2 idxXN = float2(idx.x - Off, idx.y);
                float2 idxYP = float2(idx.x, idx.y + Off);
                float2 idxYN = float2(idx.x, idx.y - Off);
        
                if (all(Projected[idxXP] == 0))
                    Projected[idxXP] += InputArray[inpIdx];
                if (all(Projected[idxXN] == 0))
                    Projected[idxXN] += InputArray[inpIdx];
                if (all(Projected[idxYP] == 0))
                    Projected[idxYP] += InputArray[inpIdx];
                if (all(Projected[idxYN] == 0))
                    Projected[idxYN] += InputArray[inpIdx];
            }
            else
                Projected[idx] = InputArray[inpIdx];
        }
    }
    Projected[idx] = InputArray[inpIdx];
}

[numthreads(8, 8, 1)]
void Gnomonic(uint3 id : SV_DispatchThreadID)
{
    uint ProjectedW, ProjectedH, ResultW, ResultH;
    Projected.GetDimensions(ProjectedW, ProjectedH);
    Result.GetDimensions(ResultW, ResultH);
    
    PI2 = PI * 2;

    float x = PI2 * (id.x / (float) ResultW - 0.5);
    float y = PI * (id.y / (float) ResultH - 0.5);

    float p = sqrt(x * x + y * y);
    float c = atan2(p, FOV);

    float sinC = sin(c);
    float cosC = cos(c);
    float sinPhi1 = sin(Rotation.x);
    float cosPhi1 = cos(Rotation.x);

    float phi = asin(cosC * sinPhi1 + y * sinC * cosPhi1 / p);
    float lambda = Rotation.y + atan2(x * sinC, (p * cosPhi1 * cosC - y * sinPhi1 * sinC));

    float2 tc = float2(lambda / (PI * 2.0) + 0.5, phi / PI + 0.5);
    tc = tc < 0 ? 1 - abs(tc) % 1 : tc % 1;
    tc.x *= ProjectedW;
    tc.y *= ProjectedH;
    
    Result[id.xy] = Projected[tc];
}