// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "Assets/SphereIntersection/Materials/Utility/Types.cginc"
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

float2 Resolution;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    
    
    Result[id.xy] = float4(id.x / Resolution.x, id.y / Resolution.y, 0, 1);
}
