float PI, PI2, FOV, FCLIP;
float2 Rotation;
float3 Position;
float Index;

#pragma kernel Translation
#pragma kernel gnomonicProjection

StructuredBuffer<float3> OffsetBuffer;
StructuredBuffer<float3> DebugOffsetBuffer;
Texture2DArray<float4> InputArray;
RWTexture2D<float4> Translated;
RWTexture2D<float4> Result;
float Off;
bool Fill;
bool Debug;

[numthreads(8, 8, 1)]
void Translation(uint3 id : SV_DispatchThreadID)
{
    PI2 = PI * 2;
    uint w, h, e, _ = 0;
    InputArray.GetDimensions(_, w, h, e, _);
    float2 Resolution = float2(w, h);
    
    float2 ll1 = id.yx / Resolution.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;
    
    float CP = InputArray[id.xyz].a * FCLIP;
    
    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P -= Position;
    P += OffsetBuffer[id.z];
    P += DebugOffsetBuffer[id.z];
    
    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float2 idx = round(a * Resolution);
    
    
    if (all(Translated[idx] == 0) || InputArray[id.xyz].a < Translated[idx].a)
    {
        if (Debug)
        {
            Translated[idx] = float4(
            sin(id.z),
            cos(id.z),
            tan(id.z),
            1);
        }
        else if (any(InputArray[id.xyz].xyz))
        {
            if (Fill)
            {
                float2 idxXP = float2(idx.x + Off, idx.y);
                float2 idxXN = float2(idx.x - Off, idx.y);
                float2 idxYP = float2(idx.x, idx.y + Off);
                float2 idxYN = float2(idx.x, idx.y - Off);
        
                if (all(Translated[idxXP] == 0))
                    Translated[idxXP] += InputArray[id.xyz];
                if (all(Translated[idxXN] == 0))
                    Translated[idxXN] += InputArray[id.xyz];
                if (all(Translated[idxYP] == 0))
                    Translated[idxYP] += InputArray[id.xyz];
                if (all(Translated[idxYN] == 0))
                    Translated[idxYN] += InputArray[id.xyz];
            }
            else Translated[idx] = InputArray[id.xyz];
        }
    }
    
}

[numthreads(8, 8, 1)]
void gnomonicProjection(uint3 id : SV_DispatchThreadID)
{
    uint TranslatedW, TranslatedH, ResultW, ResultH;
    Translated.GetDimensions(TranslatedW, TranslatedH);
    Result.GetDimensions(ResultW, ResultH);
    
    PI2 = PI * 2;

    float x = PI2 * (id.x / (float) ResultW - 0.5);
    float y = PI * (id.y / (float) ResultH - 0.5);

    float p = sqrt(x * x + y * y);
    float c = atan2(p, FOV);

    float sinC = sin(c);
    float cosC = cos(c);
    float sinPhi1 = sin(Rotation.x);
    float cosPhi1 = cos(Rotation.x);

    float phi = asin(cosC * sinPhi1 + y * sinC * cosPhi1 / p);
    float lambda = Rotation.y + atan2(x * sinC, (p * cosPhi1 * cosC - y * sinPhi1 * sinC));

    float2 tc = float2(lambda / (PI * 2.0) + 0.5, phi / PI + 0.5);
    tc = tc < 0 ? 1 - abs(tc) % 1 : tc % 1;
    tc.x *= TranslatedW;
    tc.y *= TranslatedH;
    
    Result[id.xy] = Translated[tc];
}