#define MAP_TO_RANGE(tc, targetRange) \
    (tc) * ((targetRange) - 1)

#define NORMALIZE_RANGE(tc, sourceRange) \
    (tc) / ((sourceRange) - 1)

float PI, PI2, NCLIP, FCLIP;
float2 INPUT_RESOLUTION, PROJECTION_RESOLUTION, RASTERIZATION_RESOLUTION, PREVIOUS_RASTERIZATION_RESOLUTION;


#pragma kernel LoadTexelsToQuadBuffer

Texture2D<float4> _Input;
RWStructuredBuffer<int> _Triangles;
RWStructuredBuffer<float3> _Positions;
RWStructuredBuffer<float2> _UVs;

[numthreads(1, 1, 1)]
void LoadTexelsToQuadBuffer(uint3 id : SV_DispatchThreadID)
{
    float2 uv = NORMALIZE_RANGE(id.xy, PROJECTION_RESOLUTION);
    int2 tc = MAP_TO_RANGE(uv, INPUT_RESOLUTION);
    float d = _Input[tc].a;
    /*
    // later optimize by skipping skybox verticies
    if (d == 1)
    {
        return;
    }
    */
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));
    
    P *= -1;
    
    // calculate vertex and tri indicies
    uint i00 = id.x + id.y * PROJECTION_RESOLUTION.x;
    uint i10 = i00 + 1;
    uint i01 = i00 + PROJECTION_RESOLUTION.x;
    uint i11 = i01 + 1;
    uint triIndex = i00 * 6;
    
    _Positions[i00] = P;
    _UVs[i00] = uv;
    
    _Triangles[triIndex + 0] = i00;
    _Triangles[triIndex + 1] = i11;
    _Triangles[triIndex + 2] = i10;
    _Triangles[triIndex + 3] = i11;
    _Triangles[triIndex + 4] = i00;
    _Triangles[triIndex + 5] = i01;
}
