// #pragma multi_compile PASS_0 PASS_1
#define PASS_0
// include/exclude debug code
#define DEBUG

int DEBUG_MODE, DEBUG_INT;
float PI, PI2, TIMESTEP;
float2 INPUT_RESOLUTION, PROJECTION_RESOLUTION, RASTERIZATION_RESOLUTION;
float3 OFFSET;
float4x4 MVP;

Texture2D<float4> Input;
RWTexture2D<float> ProjectedDepth, RasterizedDepth;
RWTexture2D<float2> Projected0, Projected1, Projected2, Projected3;
RWTexture2D<float4> MotionVectors, Rasterized;
SamplerState sampler_linear_repeat;


#include "PreprocessorDefines.cginc"
#include "Geometry.cginc"
#include "Rasterizer.cginc"


#pragma kernel CalculateMotionVectors

[numthreads(8, 8, 1)]
void CalculateMotionVectors(uint3 id : SV_DispatchThreadID)
{
    float2 uv = NORMALIZE_RANGE(id.xy, INPUT_RESOLUTION);
    float d = Input[id.xy].a;
    
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));
    
    MotionVectors[id.xy] = float4(P, 1);
}

#pragma kernel Project

float3 project(float3 P)
{
#ifdef DEBUG
    if (DEBUG_MODE == DEBUG_MODE_Z_SINE)
    {
        P.y += sin(TIMESTEP / 50) * sin(length(P)) * sin(P.x);
    }
#endif

    float d = length(P);

    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z));

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI);
    a.x += 0.5;

    return float3(a, d);
}

void PopulateWithTextures(int2 tc, inout ProjectedPoint points[QUAD_VERTEX_COUNT])
{
    uint2 off = uint2(1, 0);
    points[0].oc = tc;          // (0, 0)
    points[1].oc = tc + off;    // (1, 0)
    points[2].oc = tc + off.yx; // (0, 1)
    points[3].oc = tc + off.xx; // (1, 1)
    
    [unroll(QUAD_VERTEX_COUNT)]
    for (int i = 0; i < QUAD_VERTEX_COUNT; i++)
    {
        points[i].oc %= PROJECTION_RESOLUTION;
        points[i].uv = Projected[points[i].oc];
        points[i].pc = MAP_TO_RANGE(points[i].uv, RASTERIZATION_RESOLUTION);
        points[i].col = float4(1, 0, 1, 1);
        points[i].valid = VALID_POINT(points[i]);
        
        points[i].d = ProjectedDepth[points[i].oc];
    }
}

[numthreads(8, 8, 1)]
void Project(uint3 id : SV_DispatchThreadID)
{
    int2 tc = REMAP_TO_RANGE(id.xy, PROJECTION_RESOLUTION, INPUT_RESOLUTION);
    if (Input[tc].a == 1)
    {
        Projected[id.xy] = float2(-1, -1);
        return;
    }
    float3 P = MotionVectors[tc].xyz;

#ifdef DEBUG
    if (DEBUG_MODE == DEBUG_MODE_Z_SINE)
    {
        P.y += sin(TIMESTEP / 50) * sin(length(P)) * sin(P.x);
    }
#endif
    

    float4 pos4 = float4(P, 1);
    float4 transformedPosition = mul(MVP, pos4);
    float2 screenCoords = (transformedPosition.xy / transformedPosition.w) * 0.5 + 0.5;
    if (transformedPosition.w <= 0 || screenCoords.x < 0 || screenCoords.y < 0)
    {
        Projected[id.xy] = float2(-1, -1);
    }
    else
    {
        Projected[id.xy] = screenCoords;
        ProjectedDepth[id.xy] = transformedPosition.w;
    }
}


#pragma kernel Rasterize

float3 pointToVector(ProjectedPoint p)
{
    float2 ll1 = p.uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = p.d * (FCLIP - NCLIP) + NCLIP;

    return float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));
}

float3 normal(Triangle tri)
{
    float3 v0 = pointToVector(tri.v0);
    float3 v1 = pointToVector(tri.v1);
    float3 v2 = pointToVector(tri.v2);
    
    float3 edge1 = v1 - v0;
    float3 edge2 = v2 - v0;
    
    return normalize(cross(edge1, edge2));
}

bool CullTriangle(Triangle tri)
{
    float3 v0 = pointToVector(tri.v0);
    float3 v1 = pointToVector(tri.v1);
    float3 v2 = pointToVector(tri.v2);
    
    float3 edge1 = v1 - v0;
    float3 edge2 = v2 - v0;
    float3 normal = normalize(cross(edge1, edge2));
    float3 viewVector = -v0;
    float dotProduct = dot(normal, viewVector);
    
    return dotProduct <= 0.0;
}

void LoadTriangleColorData(inout Triangle tri)
{
    tri.v0.col = Input[REMAP_TO_RANGE(tri.v0.oc, PROJECTION_RESOLUTION, INPUT_RESOLUTION)];
    tri.v1.col = Input[REMAP_TO_RANGE(tri.v1.oc, PROJECTION_RESOLUTION, INPUT_RESOLUTION)];
    tri.v2.col = Input[REMAP_TO_RANGE(tri.v2.oc, PROJECTION_RESOLUTION, INPUT_RESOLUTION)];
}

[numthreads(8, 8, 1)]
void Rasterize(uint3 id : SV_DispatchThreadID)
{
#ifdef DEBUG
    if (DEBUG_MODE == DEBUG_MODE_HIGHLIGHT_QUAD)
    {
        if ((int)id.x != PROJECTION_RESOLUTION.x / 2 || (int)id.y != DEBUG_INT)
        {
            return;
        }
    }
#endif

    ProjectedPoint neighbors[QUAD_VERTEX_COUNT];
    PopulateWithTextures(id.xy, neighbors);
    
    if (!VALID_POINT(neighbors[0]))
    {
        return;
    }
        
#ifdef DEBUG
    if (DEBUG_MODE == DEBUG_MODE_HIGHLIGHT_QUAD)
    {
        DrawCircle(neighbors[1].pc, DEBUG_COL_POINT_1 / 4);
        DrawCircle(neighbors[2].pc, DEBUG_COL_POINT_2 / 4);
        DrawCircle(neighbors[3].pc, DEBUG_COL_POINT_3 / 4);
    }
    else if (DEBUG_MODE == DEBUG_MODE_Z_SINE || DEBUG_MODE == DEBUG_MODE_POINT_CLOUD)
    {
        DrawCircle(neighbors[0].pc, DEBUG_COL_POINT_0 / 4);
    }
#endif
    
    
    
    Triangle t0, t1;
    t0.v0 = t1.v0 = neighbors[0];
    t0.v1 = neighbors[1];
    t1.v1 = neighbors[2];
    t0.v2 = t1.v2 = neighbors[3];

    int validVerticies = VALID_TRIANGLE_POINTS(t0);
    if (validVerticies == 3)
    {
        LoadTriangleColorData(t0);
        RasterizeTriangle(t0);
    }

    validVerticies = VALID_TRIANGLE_POINTS(t1);
    if (validVerticies == 3)
    {
        LoadTriangleColorData(t1);
        RasterizeTriangle(t1);
    }
}


#pragma kernel Interpolate

[numthreads(8, 8, 1)]
void Interpolate(uint3 id : SV_DispatchThreadID)
{
    if (Rasterized[id.xy].a == 0)
    {
        uint2 off = uint2(1, 0);
        [unroll(4)]
        for (int i = 0; i < 4; i++)
        {
            float4 c0 = Rasterized[(id.xy - off * i) % RASTERIZATION_RESOLUTION];
            float4 c1 = Rasterized[(id.xy + off * i) % RASTERIZATION_RESOLUTION];
        
            if (c0.a != 0 && c1.a != 0)
            {
                Rasterized[id.xy] = c0 / 2 + c1 / 2;
                return;
            }
        }
        
        
        [unroll(4)]
        for (i = 0; i < 4; i++)
        {
            float4 c0 = Rasterized[(id.xy - off.yx * i) % RASTERIZATION_RESOLUTION];
            float4 c1 = Rasterized[(id.xy + off.yx * i) % RASTERIZATION_RESOLUTION];
        
            if (c0.a != 0 && c1.a != 0)
            {
                Rasterized[id.xy] = c0 / 2 + c1 / 2;
            }
        }
    }
}