#define NCLIP 1
#define FCLIP 30
#define QUAD_VERTEX_COUNT 4
#define DEBUG_BLUE float4(0.2, 0.2, 1, 1)
#define DEBUG_MAX_LINE_LENGTH 200
#define DEBUG_CIRCLE_RADIUS 2
#define DEBUG_CIRCLE_RAD_POW (DEBUG_CIRCLE_RADIUS * DEBUG_CIRCLE_RADIUS)
#define MAP_TO_RANGE(tc, targetRange) \
    ((tc) * ((targetRange) - 1))
#define NORMALIZE_RANGE(tc, sourceRange) \
    ((tc) / ((sourceRange) - 1))
#define REMAP_TO_RANGE(tc, sourceRange, targetRange) \
    MAP_TO_RANGE(NORMALIZE_RANGE(tc, sourceRange), targetRange)
#define SET_RESULT_PIXEL(x, y, col) \
    Rasterized[uint2(x, y) % RASTERIZATION_RESOLUTION] = col;
#define VALID_POINT(projectedPoint) \
    !(projectedPoint.uv.x == -1 || projectedPoint.uv.y == -1)

#pragma multi_compile __ WIREFRAME

int DEBUG_MODE, DEBUG_INT;
float PI, PI2, TIMESTEP;
float2 INPUT_RESOLUTION, PROJECTION_RESOLUTION, RASTERIZATION_RESOLUTION;
float3 OFFSET;
float4x4 MVP;

Texture2D<float4> Input;
RWTexture2D<float> ProjectedDepth, RasterizedDepth;
RWTexture2D<float2> Projected;
RWTexture2D<float4> MotionVectors, Rasterized;

#include "Geometry.cginc"
#include "Rasterizer.cginc"


#pragma kernel CalculateMotionVectors

[numthreads(8, 8, 1)]
void CalculateMotionVectors(uint3 id : SV_DispatchThreadID)
{
    float2 uv = NORMALIZE_RANGE(id.xy, INPUT_RESOLUTION);
    float d = Input[id.xy].a;
    
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;
    // CP = FCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));
    
    MotionVectors[id.xy] = float4(P, 1);
}



#pragma kernel Project

float3 project(float3 P)
{
#if WIREFRAME
    if (DEBUG_MODE == 1)
    {
        P.y += sin(TIMESTEP / 50) * sin(length(P)) * sin(P.x);
    }
#endif

    float d = length(P);

    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z));

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI);
    a.x += 0.5;

    return float3(a, d);
}

float3 uvToVector(float2 uv, float d)
{
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;

    return float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));
}
/*
void WrapProjectedPointsInRange(inout ProjectedPoint p0, inout ProjectedPoint p1)
{
    // "solve" pole problem ambiguity
    int2 diff0 = abs(REMAP_TO_RANGE(p0.oc, PROJECTION_RESOLUTION, RASTERIZATION_RESOLUTION) - p0.pc);
    int2 diff1 = abs(REMAP_TO_RANGE(p1.oc, PROJECTION_RESOLUTION, RASTERIZATION_RESOLUTION) - p1.pc);
    int2 diff = abs(diff0 - diff1);
    
    if (diff.x > 100)
    {
        if (p0.pc.x < p1.pc.x)
        {
            p0.pc.x += RASTERIZATION_RESOLUTION.x;
        }
        else
        {
            p1.pc.x += RASTERIZATION_RESOLUTION.x;
        }
    }
    
    int2 delta = abs(p0.pc - p1.pc);
    if (delta.x > RASTERIZATION_RESOLUTION.x / 2)
    {
        if (p0.pc.x < p1.pc.x)
        {
            p0.pc.x += RASTERIZATION_RESOLUTION.x;
        }
        else
        {
            p1.pc.x += RASTERIZATION_RESOLUTION.x;
        }
    }
    if (delta.y > RASTERIZATION_RESOLUTION.y / 2)
    {
        if (p0.pc.y < p1.pc.y)
        {
            p0.pc.y += RASTERIZATION_RESOLUTION.y;
        }
        else
        {
            p1.pc.y += RASTERIZATION_RESOLUTION.y;
        }
    }
}
*/
void PopulateWithTextures(int2 tc, inout ProjectedPoint points[QUAD_VERTEX_COUNT])
{
    uint2 off = uint2(1, 0);
    points[0].oc = tc;          // (0, 0)
    points[1].oc = tc + off;    // (1, 0)
    points[2].oc = tc + off.yx; // (0, 1)
    points[3].oc = tc + off.xx; // (1, 1)
    
    [unroll(QUAD_VERTEX_COUNT)]
    for (int i = 0; i < QUAD_VERTEX_COUNT; i++)
    {
        points[i].oc %= PROJECTION_RESOLUTION;
        points[i].uv = Projected[points[i].oc];
        points[i].pc = MAP_TO_RANGE(points[i].uv, RASTERIZATION_RESOLUTION);
        
        points[i].d = ProjectedDepth[points[i].oc];
    }
}

[numthreads(8, 8, 1)]
void Project(uint3 id : SV_DispatchThreadID)
{
    float2 uv = NORMALIZE_RANGE(id.xy, PROJECTION_RESOLUTION);
    float d = Input[MAP_TO_RANGE(uv, INPUT_RESOLUTION)].a;
    
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;
    
    // procedurally generate a sphere
    // CP = FCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x));
    
    // float3 P = MotionVectors[REMAP_TO_RANGE(id.xy, PROJECTION_RESOLUTION, INPUT_RESOLUTION)]

#if WIREFRAME
    if (DEBUG_MODE == 1)
    {
        P.y += sin(TIMESTEP / 50) * sin(length(P)) * sin(P.x);
    }
#endif

    /*
    for only transforming one point
    if (!any(id.xy))
        P = float3(0, 0, 0);
    else
        return;
    */

    float4 pos4 = float4(P, 1);
    float4 transformedPosition = mul(MVP, pos4);
    float2 screenCoords = (transformedPosition.xy / transformedPosition.w) * 0.5 + 0.5;
    if (transformedPosition.w <= 0 || screenCoords.x < 0 || screenCoords.y < 0)
    {
        Projected[id.xy] = float2(-1, -1);
    }
    else
    {
        Projected[id.xy] = screenCoords;
    }
}


#pragma kernel Rasterize

[numthreads(8, 8, 1)]
void Rasterize(uint3 id : SV_DispatchThreadID)
{
    ProjectedPoint neighbors[QUAD_VERTEX_COUNT];
    PopulateWithTextures(id.xy, neighbors);
    
    if (!VALID_POINT(neighbors[0]))
    {
        return;
    }
    
    // Rasterized[id.xy] = float4(neighbors[0].uv, 0, 1);
#if WIREFRAME
    DrawCircle(neighbors[0].pc, DEBUG_BLUE / 4);
    // Rasterized[neighbors[0].pc] = DEBUG_BLUE;
#endif
    
    // SortQuadExtremesVertically(neighbors);
    
    Triangle t0, t1;
    t0.v0 = t1.v0 = neighbors[0];
    t0.v1 = neighbors[1];
    t1.v1 = neighbors[2];
    t0.v2 = t1.v2 = neighbors[3];
    
    if (!any(neighbors[0].pc))
        return;
    
    if (VALID_POINT(t0.v0) + VALID_POINT(t0.v1) + VALID_POINT(t0.v2) > 1)
    {
        RasterizeTriangle(t0);
    }
    // RasterizeTriangle(t1);
}
