#pragma kernel RenderCubemap

// define enum constants
#define INPUT_TYPE_COLOR 0
#define INPUT_TYPE_DEPTH 1
#define DISPATCH_TARGET_MODE_FULL 0
#define DISPATCH_TARGET_MODE_DOWNSAMPLED 1
#define DISPATCH_TARGET_MODE_BOTH 2

uniform bool _UseDepthMask;
uniform int _InputType, _DispatchTargetMode, _InputSliceOffset;
uniform float _MapNearClip, _MapFarClip, _CamFarClip;
uniform int2 _InputResolution, _DispatchResolution, _OutputResolutionFull, _OutputResolutionDownsampled;
uniform float3 _Offset;
uniform float4x4 _OrientationMatricies[6];

Texture2DArray<float4> _InputColorBuffer;
Texture2DArray<int> _InputDepthBuffer, _DepthMask;
RWTexture2DArray<int> RW_OutputDepthBufferFull, RW_OutputDepthBufferDownsampled;

#include "CubemapTransformUtility.cginc"

bool ApplyDepthMask(uint3 tc, float depth)
{
    if (_UseDepthMask)
    {
        float oldDepth = asfloat(_DepthMask[tc]);
        if (oldDepth > 0 && depth + 0 >= oldDepth)
        {
            // old depth is offset by camera far clip, always renders it behind previous pass
            return false;
        }
    }
    
    return true;
}

[numthreads(8, 8, 1)]
void RenderCubemap(uint3 id : SV_DispatchThreadID)
{
    // compute texel coordinates
    float2 uv = (float2) id.xy / _DispatchResolution;
    int faceIndex = id.z; // expected to be in range 0 to 5
    
    uint2 tc = all(_InputResolution == _DispatchResolution) ? id.xy : uv * _InputResolution;
    bool isDepthLinear;
    float depth;
    
    switch (_InputType)
    {
        case INPUT_TYPE_COLOR:
            // input is a color buffer
            float4 sampled = _InputColorBuffer[uint3(tc, faceIndex + _InputSliceOffset)];
            depth = sampled.a * (_MapFarClip - _MapNearClip) + _MapNearClip; // rescale depth
            isDepthLinear = true;
            break;
        case INPUT_TYPE_DEPTH:
            // input is a depth buffer
            depth = asfloat(_InputDepthBuffer[uint3(tc, faceIndex + _InputSliceOffset)]);
            isDepthLinear = false;
            break;
        default:
            // invalid input type
            return;
    }
    
    float4 transformedUV = TransformUV(uv, depth, faceIndex, _Offset, isDepthLinear);
    int depthInt = asint(transformedUV.z); // InterlockedMin works only on int, so convert depth to int
    int oldDepthInt;
    
    if (_DispatchTargetMode == DISPATCH_TARGET_MODE_FULL || _DispatchTargetMode == DISPATCH_TARGET_MODE_BOTH)
    {
        // TODO: try different operators than floor
        uint3 targetIndex = uint3(floor(transformedUV.xy * _OutputResolutionFull), transformedUV.w);
        if (ApplyDepthMask(targetIndex, depth))
        {
            InterlockedMin(RW_OutputDepthBufferFull[targetIndex], depthInt, oldDepthInt);
        }
    }
    
    if (_DispatchTargetMode == DISPATCH_TARGET_MODE_DOWNSAMPLED || _DispatchTargetMode == DISPATCH_TARGET_MODE_BOTH)
    {
        uint3 targetIndex = uint3(floor(transformedUV.xy * _OutputResolutionDownsampled), transformedUV.w);
        if (ApplyDepthMask(targetIndex, depth))
        {
            InterlockedMin(RW_OutputDepthBufferDownsampled[targetIndex], depthInt, oldDepthInt);
        }
    }
}
