#pragma kernel Transform
#pragma kernel Merge

#define NCLIP 1
#define FCLIP 30
#define QUADRANT_1 int3( 1,  1, 0)
#define QUADRANT_2 int3( 1, -1, 1)
#define QUADRANT_3 int3(-1, -1, 2)
#define QUADRANT_4 int3(-1,  1, 3)

Texture2D<float4> Input;
RWTexture2DArray<float4> Quadrants;
RWTexture2D<float4> Result;
RWTexture2DArray<float> DepthBuffer;

float3 OFFSET;
float2 RESOLUTION;
float PI, PI2, MAX_RANGE, SCALE;
int RANGE;




int2 Project(int2 tc, bool depthBased, out float d)
{
    float2 uv = tc / RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = FCLIP;
    if (depthBased)
        CP = Input[uv * RESOLUTION].a * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );

    if (depthBased)
        P -= OFFSET;
    else
        P += OFFSET;
    // P = mul(TR, P);

    d = length(P);

    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    return (int2)round(a * RESOLUTION);
}

void FillCircle(float4 col, int2 tc)
{
    Result[tc + int2( 1,  0)] = col;
    Result[tc + int2(-1,  0)] = col;
    Result[tc + int2( 0,  1)] = col;
    Result[tc + int2( 0, -1)] = col;
}

void FillQuadrant(float4 col, int2 tc, int2 id, float d0, int3 identifier)
{
    int2 t0 = tc + id * identifier.xy;
    int3 t1 = int3(t0, identifier.z);

    float i0 = length(id) / MAX_RANGE;
    float i1 = Quadrants[t1].a;
    /*
    float d1 = Result[t0].r;
    if (d1 != 0 && d0 > d1)
        return;
    */

    float d1 = DepthBuffer[t1];

    if ((d1 == 0 || d0 < d1) && (i1 == 0 || i0 < i1))
    {
        DepthBuffer[t1] = d0;
        Quadrants[t1] = float4(col.rgb, i0);
        // Result[t1] = float4(col.rgb, i0);
        // Result[t1] = i0.xxxx;
    }
}

void FillQuadrants(float4 col, int2 tc, float depth)
{
    for (int x = 0; x < RANGE; x++)
    {
        for (int y = 0; y < RANGE; y++)
        {
            int2 id = int2(x, y);

            FillQuadrant(col, tc, id, depth, QUADRANT_1);
            FillQuadrant(col, tc, id, depth, QUADRANT_2);
            FillQuadrant(col, tc, id, depth, QUADRANT_3);
            FillQuadrant(col, tc, id, depth, QUADRANT_4);
        }
    }
}


[numthreads(8,8,1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    float4 val = Input[id.xy];
    float a = val.a;
    float d;
    int2 tc = Project(id.xy, true, d);

    // Result[tc] = float4(id.xy / RESOLUTION, 0, 1);
    // Result[tc] = val;
    FillQuadrants(val, tc, d / (FCLIP - NCLIP) - NCLIP);
    // FillCircle(float4(id.xy / RESOLUTION, 0, 0.01), tc);
}

[numthreads(8, 8, 1)]
void Merge(uint3 id : SV_DispatchThreadID)
{
    float4 quadrant1 = Quadrants[int3(id.xy, 0)];
    float4 quadrant2 = Quadrants[int3(id.xy, 1)];
    float4 quadrant3 = Quadrants[int3(id.xy, 2)];
    float4 quadrant4 = Quadrants[int3(id.xy, 3)];

    float interpolation1 = (1 - quadrant1.a);
    float interpolation2 = (1 - quadrant2.a);
    float interpolation3 = (1 - quadrant3.a);
    float interpolation4 = (1 - quadrant4.a);

    float scalar = interpolation1 + interpolation2 + interpolation3 + interpolation4;
    float4 val = float4((
        quadrant1.rgb * interpolation1 +
        quadrant2.rgb * interpolation2 +
        quadrant3.rgb * interpolation3 +
        quadrant4.rgb * interpolation4) / scalar, 1
    );
    /*
    float mask = abs(id.y - RESOLUTION.y / 2) / RESOLUTION.y * 6 - 2;
    mask = min(1, max(0, mask));
    float d;
    int2 tc = Project(id.xy, false, d);
    Result[id.xy] = Input[tc] * mask + val * (1 - mask);
    */
    // Result[id.xy] = mask.xxxx;
    // Result[id.xy] = Input[interpolated.rg * RESOLUTION];
    // Result[id.xy] = interpolated;
    Result[id.xy] = val;

    Quadrants[int3(id.xy, 0)] = float4(0, 0, 0, 0);
    Quadrants[int3(id.xy, 1)] = float4(0, 0, 0, 0);
    Quadrants[int3(id.xy, 2)] = float4(0, 0, 0, 0);
    Quadrants[int3(id.xy, 3)] = float4(0, 0, 0, 0);
    
    DepthBuffer[int3(id.xy, 0)] = float4(0, 0, 0, 0);
    DepthBuffer[int3(id.xy, 1)] = float4(0, 0, 0, 0);
    DepthBuffer[int3(id.xy, 2)] = float4(0, 0, 0, 0);
    DepthBuffer[int3(id.xy, 3)] = float4(0, 0, 0, 0);
}
