#pragma kernel Transform
#pragma kernel Merge

#define NCLIP 1
#define FCLIP 30
#define TOLERANCE 2.5

Texture2D<float4> Input;
RWTexture2D<float4> Result;
RWTexture2D<float> DepthBuffer;

float3 OFFSET;
float2 RESOLUTION;
float PI, PI2, MAX_RANGE, MIN_FLOAT;
int RANGE, FALLOFF, MAX, OFF;

int2 Project(int2 tc, bool depthBased, out float d)
{
    float2 uv = tc / RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = FCLIP;
    if (depthBased)
        CP = Input[uv * RESOLUTION].a * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
        );

    if (depthBased)
        P -= OFFSET;
    else
        P += OFFSET;
    // P = mul(TR, P);

    d = length(P);

    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
        );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
        );
    a.x += 0.5;

    return (int2)round(a * RESOLUTION);
}

[numthreads(8, 8, 1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    float4 val = Input[id.xy];
    float4 val1 = Input[id.xy + int2(1, 0)];
    float n = abs(val.a - val1.a);
    float a = val.a;
    float d;
    int2 tc = Project(id.xy, true, d);
    int2 tc1 = Project(id.xy + int2(1, 1), true, d);
    int dist = min(MAX, abs(tc.x - tc1.x));
    int r = round(RANGE * pow(dist, 2) / 20 + OFF);

    if (n > 0.8)
        return;
    if (length(val.rgb) < 0.0)
        return;
    if (val.a == 1)
        Result[tc] = float4(val.rgb, 0.9);


    for (int x = tc.x - r; x < tc.x + r; x++)
    {
        for (int y = tc.y - r; y < tc.y + r; y++)
        {
            int2 id = int2(x, y);
            float d1 = DepthBuffer[id];
            float i = max(MIN_FLOAT, pow(1 - min(1, length(id - tc) / r), FALLOFF));

            // if (d1 == 0 || d < d1 - TOLERANCE)
            if (false)
            {
                DepthBuffer[id] = d;
                Result[id] = float4(val.rgb * i, i);
            }
            else
                Result[id] += float4(val.rgb * i, i);
        }
    }
}

[numthreads(8, 8, 1)]
void Merge(uint3 id : SV_DispatchThreadID)
{
    float4 val = Result[id.xy];
    Result[id.xy] = float4(val.rgb / val.a, 1);
    DepthBuffer[id.xy] = 0;
}