#pragma kernel Transform
#pragma kernel RenderTree

#define NCLIP 1
#define FCLIP 30
#define ITERATIONS 1000

Texture2D<float4> Input;
RWTexture2D<float4> Result;
RWTexture2D<int4> Tree;

float3 OFFSET;
float2 RESOLUTION;
float PI, PI2;


int2 Project(int2 tc)
{
    float2 uv = tc / RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = Input[uv * RESOLUTION].a * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
        );

    P -= OFFSET;

    float d = length(P);

    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
        );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
        );
    a.x += 0.5;

    return (int2)round(a * RESOLUTION);
}

float ComparableDistance(int2 p0, int2 p1)
{
    return pow(p0.x - p1.x, 2) + pow(p0.y - p1.y, 2);
}

int2 ClosestNode(int2 p, int2 n0, int2 n1)
{
    float d0 = ComparableDistance(p, n0);
    float d1 = ComparableDistance(p, n1);

    if (d0 < d1)
        return n0;
    else
        return n1;
}

int2 AddNode(int2 node, int2 newNode) {
    uint coord;

    for (uint k = 0; k < ITERATIONS; k++)
    {
        int4 branch = Tree[node];
        coord = k % 2;

        if (newNode[coord] < node[coord]) {
            if (any(branch.xy))
            {
                node = branch.xy;
            }
            else
            {
                Tree[node] = int4(newNode, branch.zw);
                break;
            }
        }
        else
        {
            if (any(branch.zw))
            {
                node = branch.zw;
            }
            else
            {
                Tree[node] = int4(branch.xy, newNode);
                break;
            }
        }
    }

    return node;
}

int2 NearestNeighbor(int2 node, int2 p)
{
    int4 branches;
    int3 temp;
    int2 next, other;
    int2 best = node;
    uint k, coord;
    int3 stack[ITERATIONS];
    int ptr = -1;

    stack[++ptr] = int3(node, 0);

    for (int i = 0; i < ITERATIONS; i++)
    {
        if (ptr == -1) break;

        temp = stack[ptr--];
        node = temp.xy;
        k = temp.z;
        coord = k % 2;
        branches = Tree[node];

        if (p[coord] < node[coord]) {
            next = branches.xy;
            other = branches.zw;
        }
        else {
            next = branches.zw;
            other = branches.xy;
        }

        if (any(next)) {
            best = ClosestNode(p, best, next);
            stack[++ptr] = int3(next, k + 1);
        }

        if (any(other)) {
            float radiusSq = ComparableDistance(p, best);
            float dist = p[coord] - node[coord];

            if (radiusSq >= dist * dist) {
                best = ClosestNode(p, best, other);
                stack[++ptr] = int3(other, k + 1);
            }
        }
    }

    return best;
}


[numthreads(8, 8, 1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    int2 tc = Project(id.xy);
    Result[tc] = Input[id.xy];

    if (tc.x < 400 || tc.x > 800) return;
    if (tc.y < 100 || tc.y > 200) return;

    int2 root = round(RESOLUTION / 2);
    int2 node = AddNode(root, tc);
}


[numthreads(8, 8, 1)]
void RenderTree(uint3 id : SV_DispatchThreadID)
{
    int2 root = round(RESOLUTION / 2);
    // Result[id.xy] = float4(tc / RESOLUTION, 0, 1);
    // Result[id.xy] = float4(Tree[id.xy] / RESOLUTION.xyxy);
    // Result[id.xy] = any(Tree[id.xy]) ? (1).xxxx : (0).xxxx;

    if (id.x < 400 || id.x > 800) return;
    if (id.y < 100 || id.y > 200) return;

    int2 tc = NearestNeighbor(root, id.xy);
    Result[id.xy] = Input[tc];
}