#pragma kernel Importance

int DEBUG;
float PI, PI2, NCLIP, FCLIP;
float2 INPUT_RESOLUTION;
float3 POSITION;

Texture2D<float4> Input;
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void Importance(uint3 id : SV_DispatchThreadID)
{
    float2 uv = id.yx / (INPUT_RESOLUTION.yx - float2(1, 1));
    float2 ll1 = uv * float2(PI, PI2);
    ll1.y += PI;
    
    float CP = Input[id.xy].a * (FCLIP - NCLIP) + NCLIP;
    
    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P += POSITION;
    
    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float dif = abs(d) / FCLIP;
    uint2 idx = round(a * INPUT_RESOLUTION);
    
    float4 col = Input[id.xy];
    float4 tgt = Result[idx];
    /*      
    if (!all(col.rgb > 0.001) && !all(tgt.rgb > 0.001))
        // col = float4(id.xy / INPUT_RESOLUTION, 0, 1);
    */
    col = float4(dif, dif, dif, 1);
            
    if (id.x <= INPUT_RESOLUTION.x && id.y <= INPUT_RESOLUTION.y)
        Result[idx] = col;
    /*
    switch (DEBUG)
    {
        case 0:
            float4 col = Input[id.xy];
            float4 tgt = Result[idx];
            
            if (!all(col.rgb) && !all(tgt.rgb))
                col = float4(id.xy / INPUT_RESOLUTION, 0, 1);
            
            if (id.x <= INPUT_RESOLUTION.x && id.y <= INPUT_RESOLUTION.y)
                Result[idx] = col;
            break;
        case 1:
            Result[id.xy] = float4(a, 0, 1);
            break;
        case 2:a
            Result[idx] = float4(id.xy / INPUT_RESOLUTION, 0, 1);
            break;
        case 3:
            Result[idx] += 0.1.xxxx;
            break;
        case 4:
            Result[id.xy] = length(P - POSITION) / length(P).xxxx;
            break;
        case 5:
            for (int x = 0; x < INPUT_RESOLUTION.x; x++)
            {
                for (int y = 0; y < INPUT_RESOLUTION.y; y++)
                {
                    uint2 tc = uint2(x, y);
            
                    float2 ll1 = tc.yx / INPUT_RESOLUTION.yx * float2(PI, PI2);
                    ll1.y += PI;
    
                    float CP = Input[tc].a * (FCLIP - NCLIP) + NCLIP;
    
                    float3 P = float3(
                        CP * sin(ll1.y) * sin(ll1.x),
                        CP * cos(ll1.x),
                        CP * cos(ll1.y) * sin(ll1.x)
                    );
    
                    P += POSITION;
    
                    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
                    float2 ll2 = float2(
                        acos(P.y / d),
                        atan2(P.x, P.z)
                    );
    
                    float2 a = float2(
                        ll2.y / PI2,
                        ll2.x / PI
                    );
                    a.x += 0.5;
    
                    uint2 oIdx = round(a * INPUT_RESOLUTION);
            
                    if (length(oIdx - id.xy) < 5)
                    {
                        Result[oIdx] = Input[tc];
                        break;
                    }
                }
            }
            break;
    }
    */
}
