#include "Assets/SphereIntersection/Materials/Utility/Types.cginc"

float2 Resolution;
float PI, FOV;
float2 Rotation;
float3 Position;

#pragma kernel Translation
#pragma kernel Projection

StructuredBuffer<float3> OffsetBuffer;
Texture2DArray<float4> InputArray;
RWTexture2D<float4> Translated;
RWTexture2D<float4> Result;
bool Debug;

[numthreads(8, 8, 1)]
void Translation(uint3 id : SV_DispatchThreadID)
{
    uint m = 0, w, h, e, l;
    InputArray.GetDimensions(m, w, h, e, l);
    Resolution.x = w;
    Resolution.y = h;
    
    latlon ll1 = float2ToLatLon(id.xy / Resolution, PI);
    ll1.lon += PI;
        
    float CP = InputArray[id.xyz].a * 10;
    
    float3 P = latLonToVector(ll1, CP);
    
    P += Position;
    P += OffsetBuffer[id.z];
    
    float D = distance(float3(0, 0, 0), P);
    
    latlon ll2 = vectorToLatLon(P, D);
    
    float2 a = latLonToFloat2(ll2, PI);
    a.x += 0.5;
    
    float2 idx = round(a * Resolution);
    
    if (Debug)
    {
        Translated[idx] = float4(
            id.z == 0 ? 1 : 0,
            id.z == 1 || id.z == 3 ? 1 : 0,
            id.z == 2 || id.z == 3 ? 1 : 0,
            1);
    }
    else if (all(Translated[idx] == 0) || InputArray[id.xyz].a < Translated[idx].a)
    {
        Translated[idx] = InputArray[id.xyz];
    }
    
}

[numthreads(8, 8, 1)]
void Projection(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    Translated.GetDimensions(w, h);
    Resolution.x = w;
    Resolution.y = h;
    
    float PI2 = 2 * PI;

    float x = PI2 * (id.x / Resolution.x - 0.5);
    float y = PI * (id.y / Resolution.y - 0.5);

    float p = sqrt(x * x + y * y);
    float c = atan2(p, FOV);

    float sinC = sin(c);
    float cosC = cos(c);
    float sinPhi1 = sin(Rotation.x);
    float cosPhi1 = cos(Rotation.x);

    float phi = asin(cosC * sinPhi1 + y * sinC * cosPhi1 / p);
    float lambda = Rotation.y + atan2(x * sinC, (p * cosPhi1 * cosC - y * sinPhi1 * sinC));

    float2 tc = float2(lambda / (PI * 2.0) + 0.5, phi / PI + 0.5);
    tc = tc < 0 ? 1 - abs(tc) % 1 : tc % 1;
    
    Result[id.xy] = Translated[tc * Resolution];
}