float PI, PI2, FOV, FCLIP;
float2 Rotation;
float3 Position;
float Off;
bool Fill;
bool Debug;

#pragma kernel SetConvMaps;
#pragma kernel Projection

StructuredBuffer<float3> OffsetBuffer;
StructuredBuffer<float3> DebugOffsetBuffer;
Texture2DArray<float4> InputArray;
RWTexture2D<float2> CONV_SCREEN_LATLON;
RWTexture2D<float2> CONV_LATLON_SCREEN;
RWTexture2D<float4> Result;

float2 gnomonicProjection(float x, float y, float phi1, float lambda0, float fov)
{
    float p = sqrt(x * x + y * y);
    float c = atan2(p, FOV);

    float sinC = sin(c);
    float cosC = cos(c);
    float sinPhi1 = sin(phi1);
    float cosPhi1 = cos(phi1);

    float phi = asin(cosC * sinPhi1 + y * sinC * cosPhi1 / p);
    float lambda = lambda0 + atan2(x * sinC, (p * cosPhi1 * cosC - y * sinPhi1 * sinC));

    float2 tc = float2(lambda, phi);
    return tc < 0 ? 1 - abs(tc) % 1 : tc % 1;
}
float2 gnomonicProjection2(float2 pos, float fov)
{
    float x = PI2 * (pos.x - 0.5);
    float y = PI * (pos.y - 0.5);

    float p = sqrt(x * x + y * y);
    float c = atan2(p, fov);

    float sinC = sin(c);
    float cosC = cos(c);
    float sinPhi1 = sin(0);
    float cosPhi1 = cos(0);

    float phi = asin(cosC * sinPhi1 + y * sinC * cosPhi1 / p);
    float lambda = 0 + atan2(x * sinC, (p * cosPhi1 * cosC - y * sinPhi1 * sinC));

    return float2(lambda / (PI * 2.0) + 0.5, (phi / PI) + 0.5);
}
/*
float2 inverseGnomonicProjection(float2 latlon, float phi1, float lambda0, float fov)
{
    float phi = latlon.x;
    float lambda = latlon.y;

    float cosLambdaLambda0 = cos(lambda - lambda0);
    float cosC = sin(phi1) * sin(phi) + cos(phi1) * cos(phi) * cosLambdaLambda0;
    
    float x = (cos(phi1) * sin(phi) - sin(phi1) * cos(phi) * cosLambdaLambda0) / cosC;
    float y = (cos(phi) * sin(lambda0 - lambda0)) / cosC;
    return float2(x, y); // float2(x / PI + 0.5, y / PI2 + 0.5);
}
*/
[numthreads(8, 8, 1)]
void SetConvMaps(uint3 id : SV_DispatchThreadID)
{
    uint w1, h1, w2, h2;
    CONV_SCREEN_LATLON.GetDimensions(w1, h1);
    CONV_LATLON_SCREEN.GetDimensions(w2, h2);
    float2 r1 = float2(w1, h1);
    float2 r2 = float2(w2, h2);
    
    float x = (id.x / (float) w2 - 0.5) * PI;
    float y = (id.y / (float) h2 - 0.5) * PI2;
    
    float2 ll = gnomonicProjection(x, y, 0, 0, FOV);
    float2 tc = float2(ll.x / PI + 0.5, ll.y / PI2 + 0.5);
    
    CONV_SCREEN_LATLON[id.xy / r2 * r1] = tc;
    CONV_LATLON_SCREEN[tc * r2] = id.xy / r2;
}

[numthreads(8, 8, 1)]
void Projection(uint3 id : SV_DispatchThreadID)
{
    PI2 = PI * 2;
    uint convW, convH, inpW, inpH, outW, outH, _;
    CONV_LATLON_SCREEN.GetDimensions(convW, convH);
    InputArray.GetDimensions(inpW, inpH, _);
    Result.GetDimensions(outW, outH);
    float2 ConvRes = float2(convW, convH);
    float2 InpRes = float2(inpW, inpH);
    float2 OutRes = float2(outW, outH);
    
    float2 tc = gnomonicProjection2(id.xy / OutRes, FOV);
    float4 col = InputArray[float3(tc * InpRes, 0)];
    
    Result[id.xy] = float4(tc, 0, 1);
    Result[id.xy] = col;
    /*
    float2 ll1 = id.yx / Resolution.yx;
    // float2 ll1 = MAP_SCREEN_LATLON[id.xy];
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;
    
    float CP = InputArray[id.xyz].a * FCLIP;
    
    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P -= Position;
    P += OffsetBuffer[id.z];
    P += DebugOffsetBuffer[id.z];
    
    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float2 idx = round(a * Resolution);
    // float2 idx = MAP_LATLON_SCREEN[a * Resolution].xy * Resolution;
    
    if (all(Result[idx] == 0) || InputArray[id.xyz].a < Result[idx].a)
    {
        if (Debug)
        {
            Result[idx] = float4(
                sin(id.z),
                cos(id.z),
                tan(id.z),
                1);
        }
        else if (any(InputArray[id.xyz].xyz))
        {
            if (Fill)
            {
                float2 idxXP = float2(idx.x + Off, idx.y);
                float2 idxXN = float2(idx.x - Off, idx.y);
                float2 idxYP = float2(idx.x, idx.y + Off);
                float2 idxYN = float2(idx.x, idx.y - Off);
        
                if (all(Result[idxXP] == 0))
                    Result[idxXP] += InputArray[id.xyz];
                if (all(Result[idxXN] == 0))
                    Result[idxXN] += InputArray[id.xyz];
                if (all(Result[idxYP] == 0))
                    Result[idxYP] += InputArray[id.xyz];
                if (all(Result[idxYN] == 0))
                    Result[idxYN] += InputArray[id.xyz];
            }
            else
                Result[idx] = InputArray[id.xyz];
        }
    }
    */
}