#pragma kernel CSMain
#pragma kernel Interpolate

#define NCLIP 1
#define FCLIP 30

Texture2D<float4> Input;
RWTexture2D<float4> Transformed, Result;

float3 OFFSET;
float2 RESOLUTION;
float PI, PI2, MAG, OFF, FAC;
bool DEBUG;

int2 project(int2 tc)
{
    float2 uv = tc / RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = Input[tc].a * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P -= OFFSET;
    // P = mul(TR, P);

    float2 ll2 = float2(
        acos(P.y / length(P)),
        atan2(P.x, P.z)
    );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    return (int2)round(a * RESOLUTION);
}

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    int2 tc = project(id.xy);
    Transformed[id.xy] = float4(tc, 0, 1);
}

bool PointInTriangle(int2 p, int2 v0, int2 v1, int2 v2)
{
    float s = (v0.x - v2.x) * (p.y - v2.y) - (v0.y - v2.y) * (p.x - v2.x);
    float t = (v1.x - v0.x) * (p.y - v0.y) - (v1.y - v0.y) * (p.x - v0.x);

    if ((s < 0) != (t < 0) && s != 0 && t != 0)
        return false;

    float d = (v2.x - v1.x) * (p.y - v1.y) - (v2.y - v1.y) * (p.x - v1.x);
    return d == 0 || (d < 0) == (s + t <= 0);
}

// thanks to MBo for the idea: https://stackoverflow.com/a/61096648/13215204
int2 TransformTriangle(int2 p, int2 a0, int2 a1, int2 a2, int2 b0, int2 b1, int2 b2)
{
    // calculate determinant
    float det = (a1.y - a2.y) * (a0.x - a2.x) + (a2.x - a1.x) * (a0.y - a2.y);

    // get barycentric coordinates (3rd one is implied)
    float lambda0 = ((a1.y - a2.y) * (p.x - a2.x) + (a2.x - a1.x) * (p.y - a2.y)) / det;
    float lambda1 = ((a2.y - a0.y) * (p.x - a2.x) + (a0.x - a2.x) * (p.y - a2.y)) / det;

    // apply weighting
    return lambda0 * b0 + lambda1 * b1 + (1 - lambda0 - lambda1) * b2;
}

void DrawLine(int2 p0, int2 p1)
{
    // Iterators, counters required by algorithm
    int x, y, dx, dy, dx1, dy1, px, py, xe, ye, i;

    // Calculate line deltas
    dx = p1.x - p0.x;
    dy = p1.y - p0.y;

    // Create a positive copy of deltas (makes iterating easier)
    dx1 = abs(dx);
    dy1 = abs(dy);

    // Calculate error intervals for both axis
    px = 2 * dy1 - dx1;
    py = 2 * dx1 - dy1;

    // The line is X-axis dominant
    if (dy1 <= dx1)
    {
        // Line is rdawn left to right
        if (dx >= 0)
        {
            x = p0.x; y = p0.y; xe = p1.x;
        }
        else
        {
            // Line is rdawn right to left (swap ends)
            x = p1.x; y = p1.y; xe = p0.x;
        }

        // Result[uint2(x, y)] = float4(1, 1, 0, 0); // Draw first pixel

        // Rasterize the line
        for (int i = 0; x < xe; i++) {
            x = x + 1;

            // Deal with octants...
            if (px < 0)
            {
                px = px + 2 * dy1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    y = y + 1;
                }
                else
                {
                    y = y - 1;
                }

                px = px + 2 * (dy1 - dx1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[int2(x, y)] = float4(1, 1, 1, 0);
        }
    }
    else
    {
        // The line is Y-axis dominant
        // Line is rdawn bottom to top
        if (dy >= 0)
        {
            x = p0.x; y = p0.y; ye = p1.y;
        }
        else
        {
            // Line is rdawn top to bottom
            x = p1.x; y = p1.y; ye = p0.y;
        }

        // Result[uint2(x, y)] = float4(1, 1, 0, 0); // Draw first pixel

        // Prevent unrolling of loop
        if (y == ye)
            return;

        // Rasterize the line
        for (int i = 0; y < ye; i++)
        {
            y = y + 1;

            // Deal with octants...
            if (py <= 0)
            {
                py = py + 2 * dx1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    x = x + 1;
                }
                else
                {
                    x = x - 1;
                }

                py = py + 2 * (dx1 - dy1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[int2(x, y)] = float4(1, 1, 1, 0);
        }
    }
}


[numthreads(8, 8, 1)]
void Interpolate(uint3 id : SV_DispatchThreadID)
{
    // local coords
    int2 sc = floor(id.xy / FAC);
    int2 lc = id.xy - sc * FAC;
    
    // local quad
    int2 a0 = sc;
    int2 a1 = sc + int2(FAC, 0);
    int2 a2 = sc + int2(FAC, FAC);
    int2 a3 = sc + int2(0, FAC);

    // transformed quad
    int2 b0 = Transformed[sc].xy;
    int2 b1 = Transformed[sc + int2(1, 0)].xy;
    int2 b2 = Transformed[sc + int2(1, 1)].xy;
    int2 b3 = Transformed[sc + int2(0, 1)].xy;

    float4 col = Input[sc];

    if (!DEBUG)
        Result[b0] = col;

    if (distance(b0, b1) +
        distance(b1, b2) +
        distance(b2, b3) +
        distance(b3, b0) < OFF)
        return;

    if (distance(b0, b1) < MAG) DrawLine(b0, b1);
    if (distance(b1, b2) < MAG) DrawLine(b1, b2);
    if (distance(b2, b3) < MAG) DrawLine(b2, b3);
    if (distance(b3, b0) < MAG) DrawLine(b3, b0);

    // reprojected
    int2 t0 = TransformTriangle(sc + lc, a0, a1, a2, b0, b1, b2);
    int2 t1 = TransformTriangle(sc + lc, a0, a2, a3, b0, b2, b3);

    if (PointInTriangle(t0, b0, b1, b2) && !any(Result[t0]))
    {
        if (DEBUG)
            Result[t0] += float4(0.5, 0, 0, 0.5);
        else
            Result[t0] = col;
    }

    if (PointInTriangle(t1, b0, b2, b3) && !any(Result[t1]))
    {
        if (DEBUG)
            Result[t1] += float4(0, 0.5, 0, 0.5);
        else
            Result[t1] = col;
    }
}
