#pragma kernel Transform
#pragma kernel Interpolate

#define NCLIP 1
#define FCLIP 30
#define ITERATIONS 1000

Texture2D<float4> Input;
RWTexture2D<float4> Result, Depth;

float PI, PI2, TILE_SIZE;
float2 RESOLUTION;
float3 OFFSET;

int2 project(int2 tc, float rd, out float d)
{
    float2 uv = tc / RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = rd * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );

    P -= OFFSET;
    d = length(P);

    float2 ll2 = float2(
        acos(P.y / length(P)),
        atan2(P.x, P.z)
    );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;

    return (int2)round(a * RESOLUTION);
}

[numthreads(8, 8, 1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    float4 col = Input[id.xy];
    float d = 0;
    int2 tc = project(id.xy, col.a, d);
    int2 gc = tc - (tc % TILE_SIZE);
    // d = length(tc - gc);
    Result[tc] = col;
    float4 gco = Result[gc];
    float gcd = Depth[gc];

    if (any(col) && !any(gco) && (gcd == 0 || d < gcd))
    {
        Result[gc] = col;
        Depth[gc] = d;
    }
}


[numthreads(8, 8, 1)]
void Interpolate(uint3 id : SV_DispatchThreadID)
{
    if (any(Result[id.xy])) return;

    int2 gc = id.xy - (id.xy % TILE_SIZE);
    int2 gt = gc - TILE_SIZE;
    int2 gb = gc + TILE_SIZE;

    float4 cc = Result[gc];
    float4 ct = Result[gt];
    float4 cb = Result[gb];

    float lc = length(id.xy - gc);
    float lt = length(id.xy - gt);
    float lb = length(id.xy - gb);
    float t = lc + lt + lb;

    Result[id.xy] = cc * (lc / t) + ct * (lt / t) + cb * (lb / t);
}
