#pragma kernel Transform
#pragma multi_compile __ WIREFRAME
#define TOLERANCE 4




float PI, PI2, NCLIP, FCLIP, CAM_NCLIP, CAM_FCLIP;
float2 INPUT_RESOLUTION, GEOMETRY_RESOLUTION;
float4x4 TR;

Texture2D<float4> Input;
RWTexture2D<float> DepthBuffer;
RWTexture2D<float2> Result;




#if WIREFRAME
// Based on: https://jstutorial.medium.com/how-to-code-your-first-algorithm-draw-a-line-ca121f9a1395
void DrawLine(int2 p0, int2 p1)
{
    // Iterators, counters required by algorithm
    int x, y, dx, dy, dx1, dy1, px, py, xe, ye, i;

    // Calculate line deltas
    dx = p1.x - p0.x;
    dy = p1.y - p0.y;

    // Create a positive copy of deltas (makes iterating easier)
    dx1 = abs(dx);
    dy1 = abs(dy);

    // Calculate error intervals for both axis
    px = 2 * dy1 - dx1;
    py = 2 * dx1 - dy1;

    // The line is X-axis dominant
    if (dy1 <= dx1)
    {
        // Line is drawn left to right
        if (dx >= 0)
        {
            x = p0.x; y = p0.y; xe = p1.x;
        }
        else
        {
            // Line is drawn right to left (swap ends)
            x = p1.x; y = p1.y; xe = p0.x;
        }

        // Result[uint2(x, y)] = float4(1, 1, 1, 1); // Draw first pixel

        // Rasterize the line
        for (int i = 0; x < xe; i++) {
            x = x + 1;

            // Deal with octants...
            if (px < 0)
            {
                px = px + 2 * dy1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    y = y + 1;
                }
                else
                {
                    y = y - 1;
                }

                px = px + 2 * (dy1 - dx1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[uint2(x, y)] = float4(1, 1, 1, 1);
        }
    }
    else
    {
        // The line is Y-axis dominant
        // Line is drawn bottom to top
        if (dy >= 0)
        {
            x = p0.x; y = p0.y; ye = p1.y;
        }
        else
        {
            // Line is drawn top to bottom
            x = p1.x; y = p1.y; ye = p0.y;
        }

        // Result[uint2(x, y)] = float4(1, 1, 1, 1); // Draw first pixel
        
        // Prevent unrolling of loop
        if (y == ye)
            return;
        
        // Rasterize the line
        for (int i = 0; y < ye; i++)
        {
            y = y + 1;

            // Deal with octants...
            if (py <= 0)
            {
                py = py + 2 * dx1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    x = x + 1;
                }
                else
                {
                    x = x - 1;
                }

                py = py + 2 * (dx1 - dy1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[uint2(x, y)] = float4(1, 1, 1, 1);
        }
    }
}
#endif

float3 InterpolateTriangle(int x, int y, int2 v0, int2 v1, int2 v2)
{
    float dv = (v1.y - v2.y) * (v0.x - v2.x) + (v2.x - v1.x) * (v0.y - v2.y);
    float w0 = ((v1.y - v2.y) * (x - v2.x) + (v2.x - v1.x) * (y - v2.y)) / dv;
    float w1 = ((v2.y - v0.y) * (x - v2.x) + (v0.x - v2.x) * (y - v2.y)) / dv;
    float w2 = 1 - w0 - w1;

    return float3(w0, w1, w2);
}

void DrawRow(int x0, int y0, int x1, int2 v0, int2 v1, int2 v2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2)
{
    int sx, ex;

    if (x0 < x1)
    {
        sx = x0;
        ex = x1;
    }
    else
    {
        sx = x1;
        ex = x0;
    }

    int length = ex - sx;
    
    if (length <= 0)
        return;

    for (int i = sx; i <= ex; i++)
    {
        float3 w = InterpolateTriangle(i, y0, v0, v1, v2);
        float2 uv = (i0 * w.x + i1 * w.y + i2 * w.z) / (float2)GEOMETRY_RESOLUTION;
        float d = d0 * w.x + d1 * w.y + d2 * w.z;
        uint2 tc = uint2(i, y0);
        
        if (d < DepthBuffer[tc])
        {
            DepthBuffer[tc] = d;
            Result[tc] = float2(uv);
        }
    }
}

// Based on: http://www.sunshine2k.de/coding/java/TriangleRasterization/TriangleRasterization.html
void FillTopFlatTriangle(int2 v0, int2 v1, int2 v3, int2 p0, int2 p1, int2 p2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2)
{
    if (v0.y > v1.y) return;

    float invslope1 = (v1.x - v0.x) / (float)(v1.y - v0.y);
    float invslope2 = (v3.x - v0.x) / (float)(v3.y - v0.y);

    float curx1 = v0.x;
    float curx2 = v0.x;

    for (int scanlineY = v0.y; scanlineY <= v1.y; scanlineY++)
    {
        DrawRow(curx1, scanlineY, curx2, p0, p1, p2, i0, i1, i2, d0, d1, d2);

        curx1 += invslope1;
        curx2 += invslope2;
    }
}

// See comment above
void FillBottomFlatTriangle(int2 v1, int2 v2, int2 v3, int2 p0, int2 p1, int2 p2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2)
{
    if (v2.y < v1.y) return;

    float invslope1 = (v2.x - v1.x) / (float)(v2.y - v1.y);
    float invslope2 = (v2.x - v3.x) / (float)(v2.y - v3.y);

    float curx1 = v2.x;
    float curx2 = v2.x;

    for (int scanlineY = v2.y; scanlineY > v1.y; scanlineY--)
    {
        DrawRow(curx1, scanlineY, curx2, p0, p1, p2, i0, i1, i2, d0, d1, d2);

        curx1 -= invslope1;
        curx2 -= invslope2;
    }
}

void FillTriangle(int2 p0, int2 p1, int2 p2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2)
{
    int2 v0 = p0;
    int2 v1 = p1;
    int2 v2 = p2;
    int2 tmp;

    // Sort by height (ascending)
    if (v0.y > v1.y)
    {
        tmp = v0;
        v0 = v1;
        v1 = tmp;
    }
    if (v1.y > v2.y)
    {
        tmp = v1;
        v1 = v2;
        v2 = tmp;
    }
    if (v0.y > v1.y)
    {
        tmp = v0;
        v0 = v1;
        v1 = tmp;
    }

    int2 v3 = int2(v0.x + ((float)(v1.y - v0.y) / (float)(v2.y - v0.y)) * (v2.x - v0.x), v1.y);
    float d3 = d0 / 3 + d1 / 3 + d2 / 3; // for now
    
    FillTopFlatTriangle(v0, v1, v3, p0, p1, p2, i0, i1, i2, d0, d1, d3);
    FillBottomFlatTriangle(v1, v2, v3, p0, p1, p2, i0, i1, i2, d1, d2, d3);

#if WIREFRAME
    if (v0.y != v1.y || v0.y != v2.y)
    {
        DrawLine(v0, v1);
        DrawLine(v0, v2);
        DrawLine(v1, v2);
        DrawLine(v1, v3);
    }
#endif
}

int2 project(uint2 tc, out float2 d)
{
    float2 uv = tc / GEOMETRY_RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = Input[uv * INPUT_RESOLUTION].a * (FCLIP - NCLIP) + NCLIP;

    float4 P = float4(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x),
        1
    );

    P = mul(TR, P);

    d = float2(CP, sqrt(P.x * P.x + P.y * P.y + P.z * P.z));

    float2 ll2 = float2(
        acos(P.y / d.y),
        atan2(P.x, P.z)
    );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    return (int2)round(a * GEOMETRY_RESOLUTION);
}

bool clip(float d)
{
    return d > CAM_NCLIP && d < CAM_FCLIP;
}



[numthreads(8, 8, 1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    float2 dc, dt, db, dl, dr;
    
    uint2 tid = id.xy + uint2(0, 1);
    uint2 bid = id.xy - uint2(0, 1);
    uint2 lid = id.xy - uint2(1, 0);
    uint2 rid = id.xy + uint2(1, 0);
    
    int2 ctr = project(id.xy, dc);
    if (dc.x == FCLIP)
        return;
    
    int2 ttr = project(tid, dt);
    int2 btr = project(bid, db);
    int2 ltr = project(lid, dl);
    int2 rtr = project(rid, dr);

    if (abs(dc.x - dr.x) < TOLERANCE && abs(dc.x - dt.x) < TOLERANCE && clip(dc.y) && clip(dr.y) && clip(dt.y))
    {
        FillTriangle(ctr, rtr, ttr, id.xy, rid, tid, dc.y, dr.y, dt.y);
    }
    
    if (abs(dc.x - db.x) < TOLERANCE && abs(dc.x - dl.x) < TOLERANCE && clip(db.y) && clip(dl.y) && clip(dc.y))
    {
        FillTriangle(btr, ltr, ctr, bid, lid, id.xy, db.y, dl.y, dc.y);
    }
    
    
    float2 uv = id.xy / (float2)GEOMETRY_RESOLUTION;
    Result[ctr] = float4(uv.xy, 0, 1);
}