#pragma kernel Transform
#pragma multi_compile __ WIREFRAME
#define TOLERANCE 0.2




float PI, PI2, NCLIP, FCLIP, CAM_NCLIP, CAM_FCLIP;
float2 INPUT_RESOLUTION, GEOMETRY_RESOLUTION;
float4 OFFSET;
float4x4 TR;

Texture2D<float4> Input;
RWTexture2D<float> DepthBuffer;
RWTexture2D<float> InterpolationBuffer;
RWTexture2D<float4> Result;




#if WIREFRAME
// Based on: https://jstutorial.medium.com/how-to-code-your-first-algorithm-rdaw-a-line-ca121f9a1395
void DrawLine(int2 p0, int2 p1)
{
    // Iterators, counters required by algorithm
    int x, y, dx, dy, dx1, dy1, px, py, xe, ye, i;

    // Calculate line deltas
    dx = p1.x - p0.x;
    dy = p1.y - p0.y;

    // Create a positive copy of deltas (makes iterating easier)
    dx1 = abs(dx);
    dy1 = abs(dy);

    // Calculate error intervals for both axis
    px = 2 * dy1 - dx1;
    py = 2 * dx1 - dy1;

    // The line is X-axis dominant
    if (dy1 <= dx1)
    {
        // Line is rdawn left to right
        if (dx >= 0)
        {
            x = p0.x; y = p0.y; xe = p1.x;
        }
        else
        {
            // Line is rdawn right to left (swap ends)
            x = p1.x; y = p1.y; xe = p0.x;
        }

        // Result[uint2(x, y)] = float4(1, 1, 0, 0); // Draw first pixel

        // Rasterize the line
        for (int i = 0; x < xe; i++) {
            x = x + 1;

            // Deal with octants...
            if (px < 0)
            {
                px = px + 2 * dy1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    y = y + 1;
                }
                else
                {
                    y = y - 1;
                }

                px = px + 2 * (dy1 - dx1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[uint2(x, y)] = float4(1, 1, 0, 0);
        }
    }
    else
    {
        // The line is Y-axis dominant
        // Line is rdawn bottom to top
        if (dy >= 0)
        {
            x = p0.x; y = p0.y; ye = p1.y;
        }
        else
        {
            // Line is rdawn top to bottom
            x = p1.x; y = p1.y; ye = p0.y;
        }

        // Result[uint2(x, y)] = float4(1, 1, 0, 0); // Draw first pixel
        
        // Prevent unrolling of loop
        if (y == ye)
            return;
        
        // Rasterize the line
        for (int i = 0; y < ye; i++)
        {
            y = y + 1;

            // Deal with octants...
            if (py <= 0)
            {
                py = py + 2 * dx1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    x = x + 1;
                }
                else
                {
                    x = x - 1;
                }

                py = py + 2 * (dx1 - dy1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[uint2(x, y)] = float4(1, 1, 0, 0);
        }
    }
}
#endif

float3 InterpolateTriangle(int x, int y, int2 v0, int2 v1, int2 v2)
{
    float dv = (v1.y - v2.y) * (v0.x - v2.x) + (v2.x - v1.x) * (v0.y - v2.y);
    float w0 = ((v1.y - v2.y) * (x - v2.x) + (v2.x - v1.x) * (y - v2.y)) / dv;
    float w1 = ((v2.y - v0.y) * (x - v2.x) + (v0.x - v2.x) * (y - v2.y)) / dv;
    float w2 = 1 - w0 - w1;

    return float3(w0, w1, w2);
}

void DrawRow(int x0, int y0, int x1, int2 v0, int2 v1, int2 v2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2, float2 n)
{
    int sx, ex;

    if (x0 < x1)
    {
        sx = x0;
        ex = x1;
    }
    else
    {
        sx = x1;
        ex = x0;
    }
    
    if (ex - sx <= 0)
        return;

    for (int i = sx; i <= ex; i++)
    {
        float3 w = InterpolateTriangle(i, y0, v0, v1, v2);
        float2 uv = (i0 * w.x + i1 * w.y + i2 * w.z) / (float2)GEOMETRY_RESOLUTION;
        float d = d0 * w.x + d1 * w.y + d2 * w.z;
        uint2 tc = uint2(i, y0);
        
        if (d < DepthBuffer[tc])
        {
            InterpolationBuffer[tc] = length(v0 - v1) + length(v0 - v2) + length(v1 - v2);
            DepthBuffer[tc] = d;
            Result[tc] = float4(uv, n);
        }
    }
}

// Based on: http://www.sunshine2k.de/coding/java/TriangleRasterization/TriangleRasterization.html
void FillTopFlatTriangle(int2 v0, int2 v1, int2 v3, int2 p0, int2 p1, int2 p2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2, float2 n)
{
    if (v0.y > v1.y) return;

    float invslope1 = (v1.x - v0.x) / (float)(v1.y - v0.y);
    float invslope2 = (v3.x - v0.x) / (float)(v3.y - v0.y);

    float curx1 = v0.x;
    float curx2 = v0.x;

    for (int scanlineY = v0.y; scanlineY <= v1.y; scanlineY++)
    {
        DrawRow(curx1, scanlineY, curx2, p0, p1, p2, i0, i1, i2, d0, d1, d2, n);

        curx1 += invslope1;
        curx2 += invslope2;
    }
}

// See comment above
void FillBottomFlatTriangle(int2 v1, int2 v2, int2 v3, int2 p0, int2 p1, int2 p2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2, float2 n)
{
    if (v2.y < v1.y) return;

    float invslope1 = (v2.x - v1.x) / (float)(v2.y - v1.y);
    float invslope2 = (v2.x - v3.x) / (float)(v2.y - v3.y);

    float curx1 = v2.x;
    float curx2 = v2.x;

    for (int scanlineY = v2.y; scanlineY > v1.y; scanlineY--)
    {
        DrawRow(curx1, scanlineY, curx2, p0, p1, p2, i0, i1, i2, d0, d1, d2, n);

        curx1 -= invslope1;
        curx2 -= invslope2;
    }
}

void FillTriangle(int2 p0, int2 p1, int2 p2, int2 i0, int2 i1, int2 i2, float d0, float d1, float d2, float2 n)
{
    int2 v0 = p0;
    int2 v1 = p1;
    int2 v2 = p2;
    int2 tmp;

    // Sort by height (ascending)
    if (v0.y > v1.y)
    {
        tmp = v0;
        v0 = v1;
        v1 = tmp;
    }
    if (v1.y > v2.y)
    {
        tmp = v1;
        v1 = v2;
        v2 = tmp;
    }
    if (v0.y > v1.y)
    {
        tmp = v0;
        v0 = v1;
        v1 = tmp;
    }
    
    int2 v3 = int2(v0.x + ((float)(v1.y - v0.y) / (float)(v2.y - v0.y)) * (v2.x - v0.x), v1.y);
    float d3 = d0 / 3 + d1 / 3 + d2 / 3; // for now
    
    FillTopFlatTriangle(v0, v1, v3, p0, p1, p2, i0, i1, i2, d0, d1, d3, n);
    FillBottomFlatTriangle(v1, v2, v3, p0, p1, p2, i0, i1, i2, d1, d2, d3, n);

#if WIREFRAME
    if ((v0.y != v1.y || v0.y != v2.y) && d0 + d1 + d2 < 10)
    {
        DrawLine(v0, v1);
        DrawLine(v0, v2);
        DrawLine(v1, v2);
        DrawLine(v1, v3);
    }
#endif
}

int2 project(int2 tc, out float2 d, out float3 p)
{
    float2 uv = tc / GEOMETRY_RESOLUTION;
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = Input[uv * INPUT_RESOLUTION].a * (FCLIP - NCLIP) + NCLIP;

    float4 P = float4(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x),
        1
    );
    
    p = P;
    P -= OFFSET;
    P = mul(TR, P);
    
    d = float2(CP, length(P));

    float2 ll2 = float2(
        acos(P.y / d.y),
        atan2(P.x, P.z)
    );

    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    return (int2)round(a * GEOMETRY_RESOLUTION);
}

bool clip(float d)
{
    return d > CAM_NCLIP && d < CAM_FCLIP;
}



[numthreads(8, 8, 1)]
void Transform(uint3 id : SV_DispatchThreadID)
{
    float2 cd, td, bd, ld, rd;
    float3 cp, tp, bp, lp, rp;
    
    int2 cid = (int2)id.xy;
    int2 tid = cid + int2(0, 1);
    int2 bid = cid - int2(0, 1);
    int2 lid = cid - int2(1, 0);
    int2 rid = cid + int2(1, 0);
    
    int2 ctr = project(id.xy, cd, cp);
    if (cd.x == FCLIP)
        return;
    
    int2 ttr = project(tid, td, tp);
    int2 btr = project(bid, bd, bp);
    int2 ltr = project(lid, ld, lp);
    int2 rtr = project(rid, rd, rp);
    
    float2 n0 = normalize(cross(tp - cp, rp - cp)).xy;
    float2 n1 = normalize(cross(bp - cp, lp - cp)).xy;
    
    if (abs(cd.x - rd.x) < TOLERANCE && abs(cd.x - td.x) < TOLERANCE && clip(cd.y) && clip(rd.y) && clip(td.y))
    {
        FillTriangle(ctr, rtr, ttr, cid, rid, tid, cd.y, rd.y, td.y, n0);
    }
    
    if (abs(cd.x - bd.x) < TOLERANCE && abs(cd.x - ld.x) < TOLERANCE && clip(bd.y) && clip(ld.y) && clip(cd.y))
    {
        FillTriangle(btr, ltr, ctr, bid, lid, cid, bd.y, ld.y, cd.y, n1);
    }
    
    
    if (clip(cd.y))
    {
        float2 uv = id.xy / (float2) GEOMETRY_RESOLUTION;
        float it = length(ctr - ttr) + length(ctr - rtr) + length(ttr - rtr);
        float ib = length(ctr - btr) + length(ctr - ltr) + length(btr - ltr);
        InterpolationBuffer[ctr] = (it + ib) / 2.0;
        DepthBuffer[ctr] = cd.y;
        Result[ctr] = float4(uv, (n0 + n1) / 2.0);
    }
}