int IMG_IDX, MX_IDX;
float PI, PI2, FCLIP;
float2 InputArrayRes, ProjectionRes, ProjectedRes;
float3 Position;
Texture2DArray<half4> _InputArray;


float magnitude(float3 vec)
{
    return sqrt(
        vec.x * vec.x +
        vec.y * vec.y +
        vec.z * vec.z
    );
}

float3 latLonToVector(float2 latLon, float dist = 1)
{
    return float3(
        dist * sin(latLon.y) * sin(latLon.x),
        dist * cos(latLon.x),
        dist * cos(latLon.y) * sin(latLon.x)
    );
}

float2 vectorToLatLon(float3 vec, float dist = 1)
{
    return float2(
        acos(vec.y / dist),
        atan2(vec.x, vec.z)
    );
}

float2 translateLatLon(float2 latLon, float3 translation, float dist = 1)
{
    float3 P = latLonToVector(latLon, dist);
    P += translation;
    
    float d = magnitude(P);
    return vectorToLatLon(P, d);
}

#pragma kernel Project
float3 PositionOffset;
RWTexture2D<half4> _Result;

[numthreads(8, 8, 1)]
void Project(uint3 id : SV_DispatchThreadID)
{
    float3 inpIdx = float3(id.xy / ProjectionRes * InputArrayRes, IMG_IDX);
    
    float2 ll1 = id.yx / ProjectionRes.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;
    
    float CP = _InputArray[inpIdx].a * FCLIP;
    float2 ll2 = translateLatLon(ll1, -Position + PositionOffset, CP);
    
    float3 PMax = latLonToVector(ll1, FCLIP);
    PMax -= Position;
    PMax += PositionOffset;
    float dMax = magnitude(PMax);
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float2 idx = a * ProjectionRes;
    
    _Result[idx] = half4(id.xy / ProjectionRes, (IMG_IDX + 1) / (float) MX_IDX, 1);
}

#pragma kernel Combine
Texture2D<half4> _Input;
SamplerState linear_clamp_sampler;
RWTexture2D<half4> _Projected;

[numthreads(8, 8, 1)]
void Combine(uint3 id : SV_DispatchThreadID)
{
    half4 col = _Input.SampleLevel(linear_clamp_sampler, id.xy / ProjectedRes, 0);
    
    if (col.a == 1)
        _Projected[id.xy] = col;
}