#pragma kernel RasterizeTris
#pragma multi_compile __ WIREFRAME

float2 RESOLUTION, INTERVALL, DISTANCE;

RWTexture2D<float4> Result;

#if WIREFRAME
// Based on: https://jstutorial.medium.com/how-to-code-your-first-algorithm-draw-a-line-ca121f9a1395
void DrawLine(int2 p0, int2 p1)
{
    // Iterators, counters required by algorithm
    int x, y, dx, dy, dx1, dy1, px, py, xe, ye, i;

    // Calculate line deltas
    dx = p1.x - p0.x;
    dy = p1.y - p0.y;

    // Create a positive copy of deltas (makes iterating easier)
    dx1 = abs(dx);
    dy1 = abs(dy);

    // Calculate error intervals for both axis
    px = 2 * dy1 - dx1;
    py = 2 * dx1 - dy1;

    // The line is X-axis dominant
    if (dy1 <= dx1)
    {
        // Line is drawn left to right
        if (dx >= 0)
        {
            x = p0.x; y = p0.y; xe = p1.x;
        }
        else
        {
            // Line is drawn right to left (swap ends)
            x = p1.x; y = p1.y; xe = p0.x;
        }

        // Result[uint2(x, y)] = float4(1, 1, 1, 1); // Draw first pixel

        // Rasterize the line
        for (int i = 0; x < xe; i++) {
            x = x + 1;

            // Deal with octants...
            if (px < 0)
            {
                px = px + 2 * dy1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    y = y + 1;
                }
                else
                {
                    y = y - 1;
                }

                px = px + 2 * (dy1 - dx1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[uint2(x, y)] = float4(1, 1, 1, 1);
        }
    }
    else
    {
        // The line is Y-axis dominant
        // Line is drawn bottom to top
        if (dy >= 0)
        {
            x = p0.x; y = p0.y; ye = p1.y;
        }
        else
        {
            // Line is drawn top to bottom
            x = p1.x; y = p1.y; ye = p0.y;
        }

        // Result[uint2(x, y)] = float4(1, 1, 1, 1); // Draw first pixel

        // Rasterize the line
        for (int i = 0; y < ye; i++)
        {
            y = y + 1;

            // Deal with octants...
            if (py <= 0)
            {
                py = py + 2 * dx1;
            }
            else
            {
                if ((dx < 0 && dy < 0) || (dx > 0 && dy > 0))
                {
                    x = x + 1;
                }
                else
                {
                    x = x - 1;
                }

                py = py + 2 * (dx1 - dy1);
            }

            // Draw pixel from line span at
            // currently rasterized position
            Result[uint2(x, y)] = float4(1, 1, 1, 1);
        }
    }
}
#endif


float3 InterpolateTriangle(int x, int y, int2 v0, int2 v1, int2 v2)
{
    float dv = (v1.y - v2.y) * (v0.x - v2.x) + (v2.x - v1.x) * (v0.y - v2.y);
    float w0 = ((v1.y - v2.y) * (x - v2.x) + (v2.x - v1.x) * (y - v2.y)) / dv;
    float w1 = ((v2.y - v0.y) * (x - v2.x) + (v0.x - v2.x) * (y - v2.y)) / dv;
    float w2 = 1 - w0 - w1;

    return float3(w0, w1, w2);
}


void DrawRow(int x0, int y0, int x1, int2 v0, int2 v1, int2 v2)
{
    int sx, ex;

    if (x0 < x1)
    {
        sx = x0;
        ex = x1;
    }
    else
    {
        sx = x1;
        ex = x0;
    }

    int length = ex - sx;

    for (int i = sx; i <= ex; i++)
    {
        float3 w = InterpolateTriangle(i, y0, v0, v1, v2);

        Result[uint2(i, y0)] = float4(w, 1);
    }
}

// Based on: http://www.sunshine2k.de/coding/java/TriangleRasterization/TriangleRasterization.html
void FillTopFlatTriangle(int2 v0, int2 v1, int2 v3, int2 p0, int2 p1, int2 p2)
{
    if (v0.y > v1.y) return;

    float invslope1 = (v1.x - v0.x) / (float)(v1.y - v0.y);
    float invslope2 = (v3.x - v0.x) / (float)(v3.y - v0.y);

    float curx1 = v0.x;
    float curx2 = v0.x;

    for (int scanlineY = v0.y; scanlineY <= v1.y; scanlineY++)
    {
        DrawRow(curx1, scanlineY, curx2, p0, p1, p2);

        curx1 += invslope1;
        curx2 += invslope2;
    }
}

void FillBottomFlatTriangle(int2 v1, int2 v2, int2 v3, int2 p0, int2 p1, int2 p2)
{
    if (v2.y < v1.y) return;

    float invslope1 = (v2.x - v1.x) / (float)(v2.y - v1.y);
    float invslope2 = (v2.x - v3.x) / (float)(v2.y - v3.y);

    float curx1 = v2.x;
    float curx2 = v2.x;

    for (int scanlineY = v2.y; scanlineY > v1.y; scanlineY--)
    {
        DrawRow(curx1, scanlineY, curx2, p0, p1, p2);

        curx1 -= invslope1;
        curx2 -= invslope2;
    }
}

void RasterizeTriangle(int2 p0, int2 p1, int2 p2)
{
    int2 v0 = p0;
    int2 v1 = p1;
    int2 v2 = p2;
    int2 tmp;

    // Sort by height (ascending)
    if (v0.y > v1.y)
    {
        tmp = v0;
        v0 = v1;
        v1 = tmp;
    }
    if (v1.y > v2.y)
    {
        tmp = v1;
        v1 = v2;
        v2 = tmp;
    }
    if (v0.y > v1.y)
    {
        tmp = v0;
        v0 = v1;
        v1 = tmp;
    }

    int2 v3 = int2(v0.x + ((float)(v1.y - v0.y) / (float)(v2.y - v0.y)) * (v2.x - v0.x), v1.y);

    FillTopFlatTriangle(v0, v1, v3, p0, p1, p2);
    FillBottomFlatTriangle(v1, v2, v3, p0, p1, p2);

#if WIREFRAME
    DrawLine(v0, v1);
    DrawLine(v0, v2);
    DrawLine(v1, v2);
    DrawLine(v1, v3);
#endif
}

[numthreads(8, 8, 1)]
void RasterizeTris(int3 id : SV_DispatchThreadID)
{
    Result[id.xy * INTERVALL] = float4(id.xy, 0, 1);

    
}
