#pragma kernel Project
#pragma kernel Interpolate
#define PI 3.141592653589793238462
#define PI2 6.283185307179586476924
#define DW 20

float2 UV, PL, PR, PT, PB;
float2 RESOLUTION;
float3 POSITION;

Texture2D<float4> Input, ProjectedInput;
RWTexture2D<float4> Projected, Result;


float2 uv2ll(float2 uv)
{
    return float2(
        uv.y * PI,
        uv.x * PI2 + PI
    );
}

float2 ll2uv(float2 ll)
{
    return float2(
        ll.y / PI2 + 0.5,
        ll.x / PI
    );
}

float3 ll2vec(float2 ll, float dist = 1)
{
    return float3(
        dist * sin(ll.y) * sin(ll.x),
        dist * cos(ll.x),
        dist * cos(ll.y) * sin(ll.x)
    );
}
            
float2 vec2ll(float3 vec, float dist = 1)
{
    return float2(
        acos(vec.y / dist),
        atan2(vec.x, vec.z)
    );
}

float2 translateLatLon(float2 ll, float3 vec, float dist = 1)
{
    float3 P = ll2vec(ll, dist);
    P += vec;

    float d = length(P);
    return vec2ll(P, d);
}

uint2 wrapHorizontal(uint2 tc, uint offset = 0)
{
    return uint2((tc.x + offset) % uint(RESOLUTION.x), tc.y);
}

uint2 wrapVertical(uint2 tc, uint offset = 0)
{
    return uint2(tc.x, (tc.y + offset) % uint(RESOLUTION.y));
}


[numthreads(8,8,1)]
void Project(uint3 id : SV_DispatchThreadID)
{
    /*
    if (length(id.xy - PL) < DW)
    {
        // PL: red
        Projected[id.xy] = float4(1, 0, 0, 1);
    }

    if (length(id.xy - PR) < DW)
    {
        // PR: green
        Projected[id.xy] = float4(0, 1, 0, 1);
    }

    if (length(id.xy - PT) < DW)
    {
        // PT: yellow
        Projected[id.xy] = float4(1, 1, 0, 1);
    }

    if (length(id.xy - PB) < DW)
    {
        // PB: orange
        Projected[id.xy] = float4(1, 0.5, 0, 1);
    }
    */

    float2 uv0 = id.xy / RESOLUTION;
    float2 ll0 = uv2ll(uv0);
    float d = Input[id.xy].a;
    float2 ll1 = translateLatLon(ll0, POSITION, d);
    float2 uv1 = ll2uv(ll1);
    uint2 tc1 = uv1 * RESOLUTION;

    Projected[tc1] = float4(uv0, 0, 1);
}

[numthreads(8, 8, 1)]
void Interpolate(uint3 id : SV_DispatchThreadID)
{
    uint2 fac = uint2(2, 1);

    float2 uv = ProjectedInput[id.xy].xy;

    if (false)
    {
        Result[id.xy] = float4(uv, 0, 1);
        return;
    }

    uv = float2(0.5, 1);
    float dl, dr, dt, db;
    float2 uvl, uvr, uvt, uvb;

    for (uint i = 1; i < RESOLUTION.x; i++)
    {
        // left pixel
        if (dl == 0)
        {
            uvl = ProjectedInput[wrapHorizontal(id.xy, -i)].xy;

            if (any(uvl))
                dl = i;
        }

        // right pixel
        if (dr == 0)
        {
            uvr = ProjectedInput[wrapHorizontal(id.xy, i)].xy;

            if (any(uvr))
                dr = i;
        }

        // top pixel
        if (dt == 0)
        {
            uvt = ProjectedInput[wrapVertical(id.xy, -i)].xy;

            if (any(uvt))
                dt = i;
        }

        // bottom pixel
        if (db == 0)
        {
            uvb = ProjectedInput[wrapVertical(id.xy, i)].xy;

            if (any(uvb))
                db = i;
        }

        if (all(float4(dl, dr, dt, db)))
            break;
    }

    float d = dl + dr + dt + db;

    float wl = dr / d;
    float wr = dl / d;
    float wt = db / d;
    float wb = dt / d;

    uv = uvl * wl + uvr * wr + uvt * wt + uvb * wb;

    Result[id.xy] = float4(uv, 0, 1);
}
