#pragma kernel IterativeTransform
#define CUBEMAP_FACE_COUNT 6
#define NCLIP 0.1
#define FCLIP 30

uniform float4x4 ORIENTATION_MATRICIES[6];
uniform float4x4 INVERSE_ORIENTATION_MATRICIES[6];
uniform float3 CUBE_POSITIONS[1];
uniform float3 POSITION, PREVIOUS_POSITION;
uniform int2 INOUT_RESOLUTION, DOWNSAMPLED_RESOLUTION;
uniform bool IS_SETUP_FRAME;

RWTexture2DArray<float4> Input, InputOutput, Downsampled;

#include "IterativeTransformUtility.cginc"

float3 UVToWorldSpacePosition(float2 cubemapUV, float depth, int faceIndex, int cubemapIndex)
{
    float2 viewSpace = cubemapUV * 2 - 1; // [-1, 1] NDC
    float3 dir = float3(viewSpace, 1); // Assume direction vector
    float3 pos = dir * depth; // Scale direction by depth

    float4 worldPos = mul(ORIENTATION_MATRICIES[faceIndex], float4(pos, 1)); // World space position
    return worldPos.xyz / worldPos.w;
}

[numthreads(8, 8, 1)]
void IterativeTransform(uint3 id : SV_DispatchThreadID)
{
    float2 uv = (float2) id.xy / INOUT_RESOLUTION;
    int faceIndex = id.z % CUBEMAP_FACE_COUNT;
    int cubemapIndex = (id.z - faceIndex) / CUBEMAP_FACE_COUNT;
    
    float4 sampled = Input[id.xyz];
    float normalizedDepth = sampled.a % 1;
    
    float4 sampled2 = InputOutput[id.xyz];
    if (sampled2.a != 0)
    {
        // the texel is now obsolete and needs to be overwritten
        InputOutput[id.xyz] = float4(0, 0, 0, 0);
    }
    else if(all(id.xy < DOWNSAMPLED_RESOLUTION))
    {
        float4 sampled3 = Downsampled[id.xyz];
        if (sampled3.a == 0)
        {
            // no valid texel at current coords
            return;
        }
        
        float normalizedDepth3 = sampled3.a % 1;
        Downsampled[uint3(float2(id.xy) / INOUT_RESOLUTION * DOWNSAMPLED_RESOLUTION, id.z)] = float4(0, 0, 0, 0);
    }
    
    float normalizedDepth2 = sampled2.a % 1;
    
    // the texel is valid
    float depth = normalizedDepth * (FCLIP - NCLIP) + NCLIP;
    
    float3 worldPosition = UVToWorldSpacePosition(uv, depth, faceIndex, cubemapIndex);
    worldPosition -= PREVIOUS_POSITION + POSITION;
    // worldPosition -= POSITION;
    
    float3 localPosition = worldPosition + CUBE_POSITIONS[cubemapIndex];
    float4 transformedUV = WorldSpaceToCubemapUV(localPosition, cubemapIndex);
    
    // uint3 downsampledId = uint3((float) id.xy / (DOWNSAMPLED_RESOLUTION / INOUT_RESOLUTION), id.z);
    // InputOutput[id.xyz] = worldPos;
    InputOutput[uint3(transformedUV.xy * INOUT_RESOLUTION, transformedUV.w)] = sampled;
    Downsampled[uint3(transformedUV.xy * DOWNSAMPLED_RESOLUTION, transformedUV.w)] = sampled;
}
