#pragma kernel IterativeTransform
#define CUBEMAP_FACE_COUNT 6
#define NCLIP 0.1
#define FCLIP 30

uniform float4x4 ORIENTATION_MATRICIES[6];
uniform float4x4 INVERSE_ORIENTATION_MATRICIES[6];
uniform float3 CUBE_POSITIONS[1];
uniform float3 POSITION, PREVIOUS_POSITION;
uniform uint2 INOUT_RESOLUTION, DOWNSAMPLED_RESOLUTION;

RWTexture2DArray<float4> Input, InputOutput, Downsampled;

#include "IterativeTransformUtility.cginc"

float3 UVToWorldSpacePosition(float2 cubemapUV, float depth, int faceIndex, int cubemapIndex)
{
    float2 viewSpace = cubemapUV * 2 - 1; // [-1, 1] NDC
    float3 dir = float3(viewSpace, 1); // Assume direction vector
    float3 pos = dir * depth; // Scale direction by depth

    float4 worldPos = mul(ORIENTATION_MATRICIES[faceIndex], float4(pos, 1)); // World space position
    return worldPos.xyz / worldPos.w + PREVIOUS_POSITION;
}

[numthreads(8, 8, 1)]
void IterativeTransform(uint3 id : SV_DispatchThreadID)
{
    float2 uv = (float2) id.xy / INOUT_RESOLUTION;
    int faceIndex = id.z % CUBEMAP_FACE_COUNT;
    int cubemapIndex = (id.z - faceIndex) / CUBEMAP_FACE_COUNT;
    
    float4 sampled = InputOutput[id.xyz];
    float depth = sampled.a * (FCLIP - NCLIP) + NCLIP;
    float3 worldPos = UVToWorldSpacePosition(uv, depth, faceIndex, cubemapIndex);
    
    // float4 worldPos = GetCubemapWorldSpacePosition(uv, faceIndex, cubemapIndex, sampled.a);

    worldPos -= POSITION;
    float4 transformedUV = WorldSpaceToCubemapUV(worldPos, cubemapIndex);
    
    // uint3 downsampledId = uint3((float) id.xy / (DOWNSAMPLED_RESOLUTION / INOUT_RESOLUTION), id.z);
    
    // InputOutput[id.xyz] = worldPos;
    InputOutput[uint3(transformedUV.xy * INOUT_RESOLUTION, transformedUV.w)] = sampled;
}
