#pragma kernel IterativeTransform
#define CUBEMAP_FACE_COUNT 6
#define NCLIP 0.1
#define FCLIP 30

uniform float4x4 ORIENTATION_MATRICIES[6];
uniform float4x4 INVERSE_ORIENTATION_MATRICIES[6];
uniform float3 CUBE_POSITIONS[1];
uniform float3 POSITION;
uniform uint2 INOUT_RESOLUTION, DOWNSAMPLED_RESOLUTION;

RWTexture2DArray<float4> Input, InputOutput, Downsampled;

float4 GetCubemapWorldSpacePosition(float2 cubemapUV, int faceIndex, int cubemapIndex, float depth)
{
    depth = depth * (FCLIP - NCLIP) + NCLIP;
    float2 viewSpace = (cubemapUV * 2 - 1) * depth;
    
    float4 pos = float4(viewSpace, depth, 1);
    pos = mul(ORIENTATION_MATRICIES[faceIndex], pos);
    pos.xyz -= CUBE_POSITIONS[cubemapIndex];
    
    return pos;
}

float4 WorldSpaceToCubemapUV(float4 worldPosition, int cubemapIndex)
{
    float3 localPosition = worldPosition.xyz + CUBE_POSITIONS[cubemapIndex];

    // determine the face index by evaluating the dominant axis of the position
    int faceIndex;
    float3 absPos = abs(localPosition);
    if (absPos.x >= absPos.y && absPos.x >= absPos.z)
        faceIndex = (localPosition.x > 0) ? 0 : 1; // +x or -x
    else if (absPos.y >= absPos.x && absPos.y >= absPos.z)
        faceIndex = (localPosition.y > 0) ? 2 : 3; // +y or -y
    else
        faceIndex = (localPosition.z > 0) ? 4 : 5; // +z or -z

    float4 viewSpace = mul(INVERSE_ORIENTATION_MATRICIES[faceIndex], float4(localPosition, 1));
    float depth = length(viewSpace.xyz);
    float2 cubemapUV = (viewSpace.xy / depth) * 0.5 + 0.5;

    return float4(cubemapUV, depth, faceIndex);
}


[numthreads(8, 8, 1)]
void IterativeTransform(uint3 id : SV_DispatchThreadID)
{
    float2 uv = (float2) id.xy / INOUT_RESOLUTION;
    int faceIndex = id.z % CUBEMAP_FACE_COUNT;
    int cubemapIndex = (id.z - faceIndex) / CUBEMAP_FACE_COUNT;
    
    float4 sampled = Input[id.xyz];
    float4 worldPos = GetCubemapWorldSpacePosition(uv, faceIndex, cubemapIndex, sampled.a);
    worldPos.xyz -= POSITION;
    float4 transformedUV = WorldSpaceToCubemapUV(worldPos, cubemapIndex);
    
    // InputOutput[id.xyz] = float4(id.x & id.y, (id.x & 15) / 15.0, (id.y & 15) / 15.0, 0.0);
    // uint3 downsampledId = uint3((float) id.xy / (DOWNSAMPLED_RESOLUTION / INOUT_RESOLUTION), id.z);

    InputOutput[uint3(transformedUV.xy * INOUT_RESOLUTION, transformedUV.z)] = sampled;
}
