int IDX;
float PI, PI2, FCLIP;
float3 Position;

#pragma kernel Projection;
StructuredBuffer<float3> OffsetBuffer;
StructuredBuffer<float3> DebugOffsetBuffer;
Texture2DArray<float4> InputArray;
RWTexture2D<float4> Projected;

[numthreads(8, 8, 1)]
void Projection(uint3 id : SV_DispatchThreadID)
{
    uint InputWidth, InputHeight, InputDepth, ProjectedWidth, ProjectedHeight;
    InputArray.GetDimensions(InputWidth, InputHeight, InputDepth);
    Projected.GetDimensions(ProjectedWidth, ProjectedHeight);
    float2 InputRes = float2(InputWidth, InputHeight);
    float2 ProjectedRes = float2(ProjectedWidth, ProjectedHeight);
    
    float3 inpIdx = float3(id.xy / ProjectedRes * InputRes, IDX);
    
    float2 ll1 = id.yx / ProjectedRes.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;
    
    float CP = InputArray[inpIdx].a * FCLIP;
    
    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P -= Position;
    P += OffsetBuffer[IDX];
    P += DebugOffsetBuffer[IDX];
    
    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float2 idx = round(a * ProjectedRes);
    
    Projected[idx] = float4(id.xy / ProjectedRes, d, 1);
    // Projected[id.xy] = float4(PI, PI2, FCLIP, 1);
}

#pragma kernel Combine
Texture2D<float4> Input;
SamplerState sampler_Input;
RWTexture2D<float4> Result;

[numthreads(8, 8, 1)]
void Combine(uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    Result.GetDimensions(width, height);
    float2 ResultRes = float2(width, height);
    
    half4 old = Result[id.xy];
    half4 col = Input.SampleLevel(sampler_Input, id.xy / ResultRes, 0);
    
    if (any(col) && !any(old)) // TODO: Depth sorting (d < Projected[idx].a)
        Result[id.xy] = col;
}