int IMG_IDX, MX_IDX;
float PI, PI2, FCLIP;
float3 Position;

#pragma kernel Projection;
StructuredBuffer<half3> OffsetBuffer;
StructuredBuffer<half3> DebugOffsetBuffer;
Texture2DArray<half4> _InputArray;
RWTexture2D<half4> _Result;

[numthreads(8, 8, 1)]
void Projection(uint3 id : SV_DispatchThreadID)
{
    uint InputWidth, InputHeight, InputDepth, ResultWidth, ResultHeight;
    _InputArray.GetDimensions(InputWidth, InputHeight, InputDepth);
    _Result.GetDimensions(ResultWidth, ResultHeight);
    float2 InputRes = float2(InputWidth, InputHeight);
    float2 ResultRes = float2(ResultWidth, ResultHeight);
    
    float3 inpIdx = float3(id.xy / ResultRes * InputRes, IMG_IDX);
    
    float2 ll1 = id.yx / ResultRes.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;
    
    float CP = _InputArray[inpIdx].a * FCLIP;
    
    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * cos(ll1.x),
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    P -= Position;
    P += OffsetBuffer[IMG_IDX];
    P += DebugOffsetBuffer[IMG_IDX];
    
    float d = sqrt(P.x * P.x + P.y * P.y + P.z * P.z);
    
    float2 ll2 = float2(
        acos(P.y / d),
        atan2(P.x, P.z)
    );
    
    float2 a = float2(
        ll2.y / PI2,
        ll2.x / PI
    );
    a.x += 0.5;
    
    float2 idx = round(a * ResultRes);
    
    _Result[idx] = half4(id.xy / ResultRes, (IMG_IDX +1) / (float) MX_IDX, d / FCLIP);
}

#pragma kernel Combine
Texture2D<half4> _Input;
SamplerState sampler_Input;
RWTexture2D<half4> _Projected;

[numthreads(8, 8, 1)]
void Combine(uint3 id : SV_DispatchThreadID)
{
    uint width, height;
    _Projected.GetDimensions(width, height);
    float2 ProjectedRes = float2(width, height);
    
    half4 old = _Projected[id.xy];
    half4 col = _Input.SampleLevel(sampler_Input, id.xy / ProjectedRes, 0);
    
    if (col.a != 0) // TODO: Depth sorting (d < _Projected[idx].a)
        _Projected[id.xy] = col;
}