#pragma kernel CalculateNormals

float PI, PI2, NCLIP, FCLIP, DIST, MUL, OFF;
float2 INPUT_RESOLUTION, VIEW_DIR;

Texture2D<float4> Input;
RWTexture2D<float4> Result;

float2 id2ll(uint2 id)
{
    float2 uv = id / (INPUT_RESOLUTION - float2(1, 1));
    float2 ll = uv.yx * float2(PI, PI2);
    ll.y += PI;

    return ll;
}

float3 ll2vec(float2 ll, float d)
{
    return float3(
        d * sin(ll.y) * sin(ll.x),
        d * cos(ll.x),
        d * cos(ll.y) * sin(ll.x)
    );
}

float2 gnomonicProjection(float2 pos, float fov, float phi1, float lambda0)
{
    float x = PI2 * (pos.x - 0.5);
    float y = PI * (pos.y - 0.5);

    float p = sqrt(x * x + y * y);
    float c = atan2(p, fov);

    float sinC = sin(c); float cosC = cos(c);
    float sinPhi1 = sin(phi1); float cosPhi1 = cos(phi1);

    float phi = asin(cosC * sinPhi1 + y * sinC * cosPhi1 / p);
    float lambda = lambda0 + atan2(x * sinC, (p * cosPhi1 * cosC - y * sinPhi1 * sinC));

    return float2(lambda / PI2 + 0.5, phi / PI + 0.5);
}

[numthreads(8,8,1)]
void CalculateNormals(uint3 id : SV_DispatchThreadID)
{
    uint2 CID = id.xy;
    // uint2 CID = gnomonicProjection(id.xy / INPUT_RESOLUTION, PI / 2, VIEW_DIR.x, VIEW_DIR.y) * INPUT_RESOLUTION;
    /*
    uint2 TID = CID - uint2(0, DIST);
    uint2 BID = CID + uint2(0, DIST);
    uint2 LID = CID - uint2(DIST, 0);
    uint2 RID = CID + uint2(DIST, 0);
    */
    // CHANGE BACK TO ALPHA CHANNEL!!!
    // float CD = Input[CID].r * (FCLIP - NCLIP) + NCLIP;
    float CD = Input[CID].a * MUL + OFF;
    /*
    float TD = Input[TID].r * (FCLIP - NCLIP) + NCLIP;
    float BD = Input[BID].r * (FCLIP - NCLIP) + NCLIP;
    float LD = Input[LID].r * (FCLIP - NCLIP) + NCLIP;
    float RD = Input[RID].r * (FCLIP - NCLIP) + NCLIP;
    */
    float2 CLL = id2ll(CID);
    /*
    float2 TLL = id2ll(TID);
    float2 BLL = id2ll(BID);
    float2 LLL = id2ll(LID);
    float2 RLL = id2ll(RID);
    */
    float3 CP = ll2vec(CLL, CD);
    /*
    float3 TP = ll2vec(TLL, TD) - CP;
    float3 BP = ll2vec(BLL, BD) - CP;
    float3 LP = ll2vec(LLL, LD) - CP;
    float3 RP = ll2vec(RLL, RD) - CP;
    
    float3 n0 = cross(TP, RP);
    float3 n1 = cross(RP, BP);
    float3 n2 = cross(BP, LP);
    float3 n3 = cross(LP, TP);
    float3 n = normalize(n0 + n1 + n2 + n3);

    float sx = LD - RD;
    float sy = TD - BD;

    float3 nn = float3(2 * (RD - LD), 2 * (BD - TD), -4);

    Result[id.xy] = float4(normalize(n0).rrr, 1);
    */
    Result[id.xy] = float4(CP.xxx + DIST, 1);
    Result[id.xy] = Input[CID].aaaa;
}
