#include "UnityCG.cginc"
#include "Macros.cginc"
#pragma multi_compile __ USE_PREVIOUS_PASS


uniform bool VALIDATE_NEIGHBORS;
uniform int SLICE, NUM_PREVIOUS_SLICES;
uniform float PI, PI2, NCLIP, FCLIP, MAX_DIFFERENCE;
uniform float2 INPUT_RESOLUTION, MOTION_VECTOR_RESOLUTION, PROJECTION_RESOLUTION, PREVIOUS_RASTERIZATION_RESOLUTION;
uniform float4 P_CAM;
uniform float4 CUBE_POSITIONS[3];
uniform float4x4 VP_I;
uniform float4x4 ORIENTATION_MATRICIES[6];
uniform float4x4 INVERSE_ORIENTATION_MATRICIES[6];


#pragma kernel CalculateMotionVectors

Texture2D<float4> _Input;
RWTexture2DArray<float4> _MotionVectorsWrite;

[numthreads(8, 8, 1)]
void CalculateMotionVectors(uint3 id : SV_DispatchThreadID)
{
    uint2 off = uint2(1, 0);
    float2 uv = NORMALIZE_RANGE(id.xy, MOTION_VECTOR_RESOLUTION);
    uint2 tc = MAP_TO_RANGE(uv, INPUT_RESOLUTION);
    float d = _Input[tc].a;
    float dl = _Input[tc - off].a;
    float dr = _Input[tc + off].a;
    float dt = _Input[tc - off.yx].a;
    float db = _Input[tc + off.yx].a;

    // invalidate skybox verticies
    if (d == 1 || dl == 1 || dr == 1 || dt == 1 || db == 1)
    {
        MARK_VERTEX_INVALID(id.xy, SLICE);
    }

    float sl = abs(d - dl);
    float sr = abs(d - dr);
    float st = abs(d - dt);
    float sb = abs(d - db);
    
    // invalidate steep angles
    if (sl > MAX_DIFFERENCE || sr > MAX_DIFFERENCE || st > MAX_DIFFERENCE || sb > MAX_DIFFERENCE)
    {
        MARK_VERTEX_INVALID(id.xy, SLICE);
    }
        
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * -cos(ll1.x), // no idea why that's neccessary, y-axis was just flipped for some reason
        CP * cos(ll1.y) * sin(ll1.x)
    );
    
    _MotionVectorsWrite[uint3(id.xy, SLICE)] = float4(P, 1);
}



#pragma kernel LoadTexelsToBuffer

Texture2DArray<float4> _MotionVectors;
Texture2DArray<float4> _CubemapFaces;
SamplerState sampler_linear_repeat;
#ifdef USE_PREVIOUS_PASS
Texture2D<float4> _PreviousPass0, _PreviousPass1, _PreviousPass2, _PreviousPass3, _PreviousPass4, _PreviousPass5, _PreviousPass6, _PreviousPass7;
Texture2D<float4> _PreviousDepth0, _PreviousDepth1, _PreviousDepth2, _PreviousDepth3, _PreviousDepth4, _PreviousDepth5, _PreviousDepth6, _PreviousDepth7;
#endif

RWStructuredBuffer<int> _Triangles;
RWStructuredBuffer<float3> _Positions;
// x: u, y: v, z: perimeter, w: slice
RWStructuredBuffer<float4> _UVs;


float3 IntersectViewRayWithCubemaps(float3 viewDirection, out int faceIndex, out int cubemapIndex)
{
    int currentCubemapIndex, closestFaceIndex, closestCubemapIndex;
    float t, closestFaceDistance = MAX_INT_CONST;
    float closestCubeDistance = closestFaceDistance;
    float3 intersectionPoint, closestFaceIntersection, closestCubeIntersection = float3(0, 0, 0);
    float3 cameraPositionFaceSpace, viewDirectionFaceSpace;
    float4 cubePosition;
    float4x4 invOrientationMatrix;
    
    faceIndex = -1;
    cubemapIndex = -1;
        
    [unroll]
    for (int currentFaceIndex = 0; currentFaceIndex < CUBEMAP_FACE_COUNT; currentFaceIndex++)
    {
        // transform the view ray to face space
        invOrientationMatrix = INVERSE_ORIENTATION_MATRICIES[currentFaceIndex];
        viewDirectionFaceSpace = mul(invOrientationMatrix, float4(viewDirection, 1)).xyz;
        
        // avoid potential precision issues by checking if the ray is close to parallel to the face
        if (viewDirectionFaceSpace.z > 0.0001)
        {
            [unroll]
            for (currentCubemapIndex = 0; currentCubemapIndex < 2; currentCubemapIndex++)
            {
                // transform the camera position to face space
                cubePosition = CUBE_POSITIONS[currentCubemapIndex];
                cameraPositionFaceSpace = mul(invOrientationMatrix, P_CAM - cubePosition).xyz;
            
                // shift cube faces one unit away from origin (along face normal)
                cameraPositionFaceSpace.z -= CUBEMAP_SCALE;
                
                // intersect the current face of all cubes with the view ray
                t = -cameraPositionFaceSpace.z / viewDirectionFaceSpace.z;
                intersectionPoint = cameraPositionFaceSpace + t * viewDirectionFaceSpace;

                // get the closest intersecting point
                if (all(abs(intersectionPoint) <= CUBEMAP_SCALE) && t > 0 && t < closestFaceDistance)
                {
                    closestFaceDistance = t;
                    closestFaceIntersection = intersectionPoint;
                    closestCubemapIndex = currentCubemapIndex;
                }
            }
    
            if (closestFaceDistance < closestCubeDistance)
            {
                // the initial or a closer face intersects with the view ray
                closestCubeDistance = closestFaceDistance;
                closestCubeIntersection = closestFaceIntersection;
                faceIndex = currentFaceIndex;
                cubemapIndex = closestCubemapIndex;
            }
        }
    }
    
    return closestCubeIntersection;
}

float3 ScreenToClosestCubemapFaceUV(float2 screenUV)
{
    float4 viewRayClip = float4(screenUV * 2 - 1, 0, 1);
    float3 viewRayWorld = mul(VP_I, viewRayClip).xyz;
                
    int faceIndex, cubemapIndex;
    float3 intersectionPoint = IntersectViewRayWithCubemaps(viewRayWorld, faceIndex, cubemapIndex);
    if (faceIndex == -1)
    {
        return float3(-1, -1, -1);
    }

    return float3(intersectionPoint.xy / CUBEMAP_SCALE / 2 + 0.5, 6 * cubemapIndex + faceIndex);
}

float4 GetCubemapWorldSpacePosition(float3 cubemapUV)
{
    int faceIndex = cubemapUV.z % CUBEMAP_FACE_COUNT;
    int cubemapIndex = (cubemapUV.z - faceIndex) / CUBEMAP_FACE_COUNT;
    float depth = _CubemapFaces.SampleLevel(sampler_linear_repeat, cubemapUV, 0).a;
    if (depth == 0)
    {
        return float4(0, 0, 0, -1);
    }
    depth = depth * (FCLIP - NCLIP) + NCLIP;
    
    float2 viewSpace = (cubemapUV * 2 - 1) * depth;
    float4 pos = float4(viewSpace, depth, 1);
    pos = mul(ORIENTATION_MATRICIES[faceIndex], pos);
    // pos.xyz += CUBE_POSITIONS[cubemapIndex];
    return pos;
}

float4 GetWorldSpacePositionAndTransformUV(inout float4 uv)
{
#ifdef USE_PREVIOUS_PASS
    float d0, d1 = 0;
    float2 rc = MAP_TO_RANGE(uv.xy, PREVIOUS_RASTERIZATION_RESOLUTION);
    float4 tmp;
    uv = float4(0, 0, MAX_INT_CONST, -1);
    
    // some weirdness (why does the compiler hate me) caused slice to increase above NUM_PREVIOUS_SLICES
    // unrolling the loop appears to have fixed that, although I don't see how that makes any sense
    [unroll(MAX_SLICES)]
    for (int slice = 0; slice < 6; slice++)
    {
        READ_PSEUDO_ARRAY(_PreviousDepth, rc, slice, d0);
        
        // check if slice is invalid or behind the current layer
        if (d0 == 0 || d0 < d1 - DEPTH_TOLERANCE)
        {
            continue;
        }
    
        READ_PSEUDO_ARRAY(_PreviousPass, rc, slice, tmp);
        
        // sort using depth layers
        if (d0 > d1 + DEPTH_TOLERANCE || tmp.z < uv.z)
        {
            // new closest layer, clear least blurry slices
            // pixel is in current layer, compare blurryness values
            uv = tmp;
            d1 = d0;
        }
    }
#else
    uv.xyw = ScreenToClosestCubemapFaceUV(uv.xy);
#endif
    
    return _MotionVectors.SampleLevel(sampler_linear_repeat, uv.xyw, 0);
    // return GetCubemapWorldSpacePosition(uv.xyw);
}

bool neighborsValid(float2 uv, int s)
{
    uint3 tc = uint3(MAP_TO_RANGE(uv, INPUT_RESOLUTION), s);
    
    tc.x -= 1;
    if (_MotionVectors[tc].w == 0)
        return false;
    
    tc.x += 2;
    if (_MotionVectors[tc].w == 0)
        return false;
    
    tc.xy -= 1;
    if (_MotionVectors[tc].w == 0)
        return false;
    
    tc.y += 2;
    if (_MotionVectors[tc].w == 0)
        return false;
    
    return true;
}

float2 vectorToUV(float3 vec)
{
    return float2(
        atan2(vec.x, vec.z),
        -acos(vec.y / length(vec))
    ) / float2(PI2, PI) + float2(0.5, 0);
}
            
float getRaySphereDistance(float3 a, float3 b, float3 c)
{
    float numerator = length(cross(c - a, c - b));
    return numerator / length(b - a);
}

float3 approximateClosestSliceUV(inout float4 uv)
{
    float4 clipPos = float4(uv.xy * 2.0 - 1.0, 1, 1.0);
    float4 worldPos = mul(VP_I, clipPos);
    float3 P = worldPos.xyz / worldPos.w;
    float2 tc = vectorToUV(P - P_CAM.xyz);
    uv = float4(uv.xyz, uv.w);
    return P - P_CAM.xyz;
}

[numthreads(1, 1, 1)]
void LoadTexelsToBuffer(uint3 id : SV_DispatchThreadID)
{
    // calculate vertex and tri indicies
    uint i00 = id.x + id.y * PROJECTION_RESOLUTION.x;
    uint i10 = i00 + 1;
    uint i01 = i00 + PROJECTION_RESOLUTION.x;
    uint i11 = i01 + 1;
    uint triIndex = i00 * 6;
    
    float4 uv = float4(NORMALIZE_RANGE(id.xy, PROJECTION_RESOLUTION), 0, SLICE);
    float3 P_tmp;
#ifndef USE_PREVIOUS_PASS
    if (id.x > 150)
    {
        // P_tmp.xyz = approximateClosestSliceUV(uv);
        
    }
    // uv.w = id.x > 150;
#endif
    
    float4 P = GetWorldSpacePositionAndTransformUV(uv);
#ifndef USE_PREVIOUS_PASS
    // P = id.x > 150 ? P_tmp.xyzz : P;
    /*
    if (VALIDATE_NEIGHBORS && !neighborsValid(uv.xy, uv.w))
    {
        uv.x += 1;
    }
    */
#endif
    
    _Positions[i00] = P.xyz;
    _UVs[i00] = uv;
    
    _Triangles[triIndex + 0] = i00;
    _Triangles[triIndex + 1] = i11;
    _Triangles[triIndex + 2] = i10;
    _Triangles[triIndex + 3] = i11;
    _Triangles[triIndex + 4] = i00;
    _Triangles[triIndex + 5] = i01;
}
