#pragma multi_compile __ USE_PREVIOUS_PASS

#define MAP_TO_RANGE(tc, targetRange) \
    (tc) * ((targetRange) - 1)

#define NORMALIZE_RANGE(tc, sourceRange) \
    (tc) / ((sourceRange) - 1)

#define VERTICIES_PER_QUAD 6

int TEXTURE_INDEX;
float PI, PI2, NCLIP, FCLIP;
float2 INPUT_RESOLUTION, PROJECTION_RESOLUTION, PREVIOUS_RASTERIZATION_RESOLUTION;

#pragma kernel CalculateMotionVectors

Texture2D<float4> _Input;
RWTexture2DArray<float4> _MotionVectorsWrite;

[numthreads(8, 8, 1)]
void CalculateMotionVectors(uint3 id : SV_DispatchThreadID)
{
    float2 uv = NORMALIZE_RANGE(id.xy, INPUT_RESOLUTION);
    float d = _Input[id.xy].a;
    
    // invalidate skybox verticies
    if (d == 1)
    {
        _MotionVectorsWrite[uint3(id.xy, TEXTURE_INDEX)] = float4(0, 0, 0, 0);
        return;
    }
        
    float2 ll1 = uv.yx;
    ll1.x *= PI;
    ll1.y *= PI2;
    ll1.y += PI;

    float CP = d * (FCLIP - NCLIP) + NCLIP;

    float3 P = float3(
        CP * sin(ll1.y) * sin(ll1.x),
        CP * -cos(ll1.x), // no idea why that's neccessary, y-axis was just flipped for some reason
        CP * cos(ll1.y) * sin(ll1.x));
    
    _MotionVectorsWrite[uint3(id.xy, TEXTURE_INDEX)] = float4(P, 1);
}



#pragma kernel LoadTexelsToBuffer

Texture2DArray<float4> _MotionVectors;
#ifdef USE_PREVIOUS_PASS
Texture2D<float4> _PreviousPass;
SamplerState sampler_linear_repeat;
#endif

RWStructuredBuffer<int> _Triangles;
RWStructuredBuffer<float3> _Positions;
RWStructuredBuffer<float2> _UVs;

[numthreads(1, 1, 1)]
void LoadTexelsToBuffer(uint3 id : SV_DispatchThreadID)
{
    // calculate vertex and tri indicies
    uint i00 = id.x + id.y * PROJECTION_RESOLUTION.x;
    uint i10 = i00 + 1;
    uint i01 = i00 + PROJECTION_RESOLUTION.x;
    uint i11 = i01 + 1;
    uint triIndex = i00 * 6;
    
    float2 uv = NORMALIZE_RANGE(id.xy, PROJECTION_RESOLUTION);
    
#ifdef USE_PREVIOUS_PASS
    float4 pc = _PreviousPass[MAP_TO_RANGE(uv, PREVIOUS_RASTERIZATION_RESOLUTION)];
    if (pc.a == 0)
    {
        _UVs[i00] = float2(-1, 0);
        return;
    }
    
    uv = pc.xy;
    float4 P = _MotionVectors.SampleLevel(sampler_linear_repeat, float3(uv, TEXTURE_INDEX), 0);
    int2 tc = MAP_TO_RANGE(uv, INPUT_RESOLUTION);
#else
    int2 tc = MAP_TO_RANGE(uv, INPUT_RESOLUTION);
    float4 P = _MotionVectors[uint3(tc, TEXTURE_INDEX)];
#endif
    
    if (P.w == 0)
    {
        // skip invalid verticies
        _UVs[i00] = float2(-1, 0);
        return;
    }
    
    _Positions[i00] = P.xyz;
    _UVs[i00] = uv;
    
    _Triangles[triIndex + 0] = i00;
    _Triangles[triIndex + 1] = i11;
    _Triangles[triIndex + 2] = i10;
    _Triangles[triIndex + 3] = i11;
    _Triangles[triIndex + 4] = i00;
    _Triangles[triIndex + 5] = i01;
}
